### PR TITLE
WX-697: Update Cromwell version to 0.2.174

### PR DESCRIPTION
**Pull request by broadbot**
This PR is auto-generated by
[Cromwhelm actions/make_leo_pr](https://github.com/broadinstitute/cromwhelm/blob/main/.github/workflows/make_leo_pr.yml), using
[github actions/github-script](https://github.com/actions/github-script).

It updates cromwell-helm from version 0.2.173 to 0.2.174.

### CODE REVIEW

**Review by rtitle — APPROVED** [review]
👍 , will make sure this goes through

**Comment by rtitle** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
Jenkins retest

**Comment by rtitle** [comment]
jenkins retest

**Pull request merged**
