### PR TITLE
[IA-3545][IA-3558] update images hail 1.0.19 aou 2.1.7 and cos update

### PR DESCRIPTION
**Pull request by xuscrbw**
This is a PR to bump Hail and AOU versions. 
I also had been seeing this flakiness with the PyKernelSpec a few times, so I added a fix for it.
It seems like the query succeeds, but it does not seem to always display this "Current Status: DONE" text, which is causing the tests to fail. Removing this since we check the result of the query, which I think is more important.
---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by gpcarr — APPROVED** [review]

**Comment by xuscrbw** [comment]
jenkins retest

**Comment by xuscrbw** [comment]
jenkins retest

**Comment by xuscrbw** [comment]
jenkins retest

**Comment by xuscrbw** [comment]
jenkins multi-test

**Comment by xuscrbw** [comment]
jenkins retest

**Pull request merged**
