### PR TITLE
allow all terra.bio domains via wildcard in csp

### PR DESCRIPTION
**Pull request by MatthewBemis**
\<your comments for this PR go here\>

Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by rtitle — APPROVED** [review]
Looks good. Did you confirm this actually works?

**Comment by MatthewBemis** [comment]
jenkins retest

**Comment by MatthewBemis** [comment]
@rtitle no i didn't confirm that this works yet. i will do so by modifying the CSP for one of my own prod clusters to match this and then see if it still works on terra.bio domains

**Comment by MatthewBemis** [comment]
jenkins retest

**Comment by MatthewBemis** [comment]
@rtitle i've confirmed that this works on production by modifying `jupyter_notebook_config.py` directly on a production cluster. for a sanity check, i did a negative test case with no terra.bio domains (which resulted in a blank page), and then applied the *.terra.bio domain and it worked as expected.

will merge once tests go green. i'll likely need to apply this change manually to production because i doubt this will be on the next release train.

**Comment by rtitle** [comment]
cool, :shipit:

**Comment by MatthewBemis** [comment]
jenkins retest

**Comment by MatthewBemis** [comment]
jenkins retest

**Pull request merged**
