### PR TITLE
[SUP-799] Add to csp

### PR DESCRIPTION
**Pull request by jdcanas**
This is for plotly and openstreetmap

### CODE REVIEW

**Review by lucymcnatt — APPROVED** [review]

**Comment by jdcanas** [comment]
jenkins retest

**Comment by jdcanas** [comment]
jenkins retest

**Comment by jdcanas** [comment]
jenkins retest

**Comment by jdcanas** [comment]
jenkins retest

**Comment by jdcanas** [comment]
jenkins retest

**Comment by jdcanas** [comment]
jenkins retest

**Comment by jdcanas** [comment]
jenkins retest

**Pull request merged**
