### PR TITLE
QA-2053: Update Leo contract tests to use new publish-contracts API. Deprecate publish-pacts API.

### PR DESCRIPTION
**Pull request by ichengchang**
Jira ticket: [QA-2053](https://broadworkbench.atlassian.net/browse/QA-2053)

**Description**

Previous effort publish consumer contracts was based on the pb:publish-pact endpoint. We are changing to the new pb:publish-contracts endpoint as [Pact Broker doc](https://pact-broker.dsp-eng-tools.broadinstitute.org/hal-browser/browser.html#https://pact-broker.dsp-eng-tools.broadinstitute.org) recommended.

**A/C**

In `consumer_contract_tests.yml` GHA, deprecate the `publish-pacts` GHA and replace it with new GHA https://github.com/broadinstitute/terra-github-workflows/blob/main/.github/workflows/publish-contracts.yaml . 

The new GHA only requires the following parameters, more straightforward to use than the previous GHA. 

pact-b64:        description: 'Pact content formatted as non-breaking base64 string'

repo-owner:     description: 'The git repo owner

repo-name:      description: 'The git repo name'

repo-branch:    description: 'The git branch name'

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

[QA-2053]: https://broadworkbench.atlassian.net/browse/QA-2053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by LizBaldo — APPROVED** [review]
LGTM! Happy to monitor the tests and merge for you if this is annoying :)

**Comment by LizBaldo** [comment]
jenkins retest

**Comment by ichengchang** [comment]
> LGTM! Happy to monitor the tests and merge for you if this is annoying :)

Thanks for the approval! It's OK, I can monitor the Jenkins test and rerun it as needed.

**Comment by ichengchang** [comment]
jenkins retest

**Comment by ichengchang** [comment]
jenkins retest

**Pull request merged**
