### PR TITLE
mv gsutil delocalize to the background

### PR DESCRIPTION
**Pull request by calbach**
This makes the UI a bit snappier on save, rename, delete.

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by calbach** [comment]
I can't see the Jenkins page, but I'd guess it's unrelated to my PR.

**Comment by rtitle** [comment]
Yeah it always fails on PR from forks :(

On my list to fix

**Comment by calbach** [comment]
FYI: I invaded your repo on this one with my topic branch - no fork. Possibly a different issue.

**Comment by rtitle** [comment]
Oh I see -- we tag the docker image with the branch name and it doesn't like the slash in this case:

```
invalid argument "broadinstitute/leonardo-notebooks:ch/invalidate-deloc" for t: Error parsing reference: "broadinstitute/leonardo-notebooks:ch/invalidate-deloc" is not a valid repository/tag
```

**Comment by calbach** [comment]
Per offline discussion @rtitle, we don't think it's worth recreating the PR with a different branch name and this code isn't currently covered by Jenkins anyways. I will omit /'s going forward.

**Pull request merged**
