### PR TITLE
Change Cromwell version (BW-902).

### PR DESCRIPTION
**Pull request by cahrens**
Updating to new Cromwell helm chart version.

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by cjllanwarne — APPROVED** [review]

**Review by kpierre13 — APPROVED** [review]

**Review by Qi77Qi — APPROVED** [review]

**Comment by cahrens** [comment]
jenkins retest

**Comment by cahrens** [comment]
The Cromwhelm pages setting was set to a branch instead of main. My fault because I forgot to put it back on Friday after I updated my fiab.

**Comment by cahrens** [comment]
jenkins retest

**Comment by cahrens** [comment]
jenkins retest

**Pull request merged**
