### PR TITLE
[RW-10295] Bump AoU RStudio Helm Chart version

### PR DESCRIPTION
**Pull request by yonghaoy**
__Jira ticket__: https://precisionmedicineinitiative.atlassian.net/browse/RW-10295

## Summary of changes

Needed for https://github.com/DataBiosphere/terra-app/pull/41

### What

-

### Why

-

### What to test

- 

### Who tested and where

- [ ] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [ ] I validated this change 
- [ ] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

### CODE REVIEW

**Comment by Qi77Qi** [comment]
@yonghaoy  It'd nice to test it locally first before we merge it in Leo...but if AoU is the only consumer of the chart, it probaby doesn't really hurt much to merge

**Comment by yonghaoy** [comment]
> 

Thanks! AoU RStudio is only in dev so nothing should be broken. I am trying to get my Bee setup but it's bit challenging. :(

**Comment by LizBaldo** [comment]
Happy to add you on my BEE @yonghaoy if you like

**Comment by LizBaldo** [comment]
haha thanks @yonghaoy I was about to push a fix and you beat me to it :) I am syncing my BEE with this change and will test creating an RStudio app with a Workspace name as a custom env variable

**Comment by LizBaldo** [comment]
@yonghaoy I think this is good! I pointed my BEE to these changes, and was able to create an RSTUDIO app with the following request body:
```
{
  "diskConfig": {
    "name": "disk10"
  },
  "appType": "RSTUDIO",
  "customEnvironmentVariables": {
    "WORKSPACE_NAME": "test-cert-rotation"
  }
}
```

I can confirm that the app is now running, and I do see the workspace name 🎉 

Screenshot 2023-06-16 at 10 14 50 AM
Screenshot 2023-06-16 at 10 13 40 AM

**Review by LizBaldo — APPROVED** [review]

**Comment by yonghaoy** [comment]
jenkins retest

**Comment by yonghaoy** [comment]
jenkins retest

**Comment by yonghaoy** [comment]
jenkins retest

**Pull request merged**
