### PR TITLE
IA-1632 Don't publish image to dockerhub

### PR DESCRIPTION
**Pull request by Qi77Qi**
part of https://broadworkbench.atlassian.net/browse/IA-1632

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by rtitle** [comment]
I seem to recall there is some piece of our CI which still checks dockerhub - maybe something in fiab deployment? Let me look…

**Comment by rtitle** [comment]
Here it is. 
- fiab docker-compose reads from Dockerhub :facepalm:
   - https://github.com/broadinstitute/firecloud-develop/blob/dev/run-context/fiab/configs/leonardo/docker-compose.yaml.ctmpl#L22
- live docker-compose reads from GCR:
   - https://github.com/broadinstitute/firecloud-develop/blob/dev/run-context/live/configs/leonardo/docker-compose.yaml.ctmpl#L4

There may be other things lurking too. We should make sure we review all CI/CD before removing the dockerhub push.

**Review by rtitle — CHANGES_REQUESTED** [review]
Check CI/CD scripts

**Comment by Qi77Qi** [comment]
@rtitle  https://github.com/broadinstitute/firecloud-develop/pull/2001

**Comment by rtitle** [comment]
The fc-develop test run failed… not sure we can merge this until https://github.com/broadinstitute/firecloud-develop/pull/2001 is merged, right? Otherwise fiabs will fail to find the right images in dockerhub.

Actually, I'm not sure how this PR test run passed 🤔

**Comment by rtitle** [comment]
OK, _now_ I think this PR along with https://github.com/broadinstitute/firecloud-develop/pull/2008 should be good. Will merge when tests pass

**Review by rtitle — APPROVED** [review]

**Comment by rtitle** [comment]
Failed with `"e6562d07b6d53eff1bc645d231d7d9cc9316430b" did not start with substring "ed93873"`. So we still have some issue.

It seems different though.. the correct dev welder hash is `e6562d0`. This seems like the Leo version is correct on the fiab, but it's using an old _test_ image. Hmm..

**Comment by rtitle** [comment]
Ah, it's because this PR skips building `Dockerfile-tests` which is still in dockerhub only. Gonna look at 1 more change

**Pull request merged**
