### PR TITLE
Cache AoU 2.0.1 and 2.0.4 to experiment with reduced e2e flakes

### PR DESCRIPTION
**Pull request by calbach**
**Do not merge**: before this week's (~12/7) Terra release

With >2.0.1, we're seeing high numbers of flakes in the AoU test env. Reverting to 2.0.1 causes runtime creation to fail, presumably because 2.0.1 is uncached and is too large.

### CODE REVIEW

**Comment by yonghaoy** [comment]
multi-test

**Comment by calbach** [comment]
FYI @Qi77Qi I got a custom image build, which created images but failed in the later steps. Will need your confirmation these images are safe to use: https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-custom-image-wilson/32/

**Review by Qi77Qi — APPROVED** [review]

**Review by yonghaoy — APPROVED** [review]

**Comment by calbach** [comment]
Jenkins failed with 10m timeout on : `org.broadinstitute.dsde.workbench.leonardo.notebooks.NotebookHailSpec.NotebookHailSpec should install the right Hail version`

jenkins retest

**Comment by calbach** [comment]
jenkins retest

**Pull request merged**
