### PR TITLE
[IA-2443] Add AppSec GitHub Trivy Action

### PR DESCRIPTION
**Pull request by dinvlad**
This change adds Trivy security scan for the Docker image, as discussed in the Workbench Cross-Team meeting.

The action will run on every PR and give you feedback if the Docker image contains critical OS vulnerabilities.

More info:
https://github.com/broadinstitute/dsp-appsec-trivy-action
https://github.com/broadinstitute/dsp-appsec-blessed-images

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by Qi77Qi — APPROVED** [review]
lgtm as long as tests pass :)

**Comment by dinvlad** [comment]
Seems like underlying Jenkins passed?

**Comment by Qi77Qi** [comment]
seems just flakey test...jenkins retest

**Comment by Qi77Qi** [comment]
leo build failed..jenkins retest

**Comment by rtitle** [comment]
Just rebased this, hopefully tests pass

**Review by rtitle — APPROVED** [review]

**Pull request merged**
