### PR TITLE
Add back Jupydocker ENTRYPOINT

### PR DESCRIPTION
**Pull request by rtitle**
For the user scripts change (https://github.com/DataBiosphere/leonardo/pull/170/) we removed `ENTRYPOINT [pyspark]` from the Dockerfile, and started calling `docker exec -d pyspark` in the init script. We did this so the user script has a chance to run before pyspark starts.

However I think this doesn't actually work: you can't docker exec against a container with no entrypoint. I am getting this when creating clusters:
```
+ docker exec -u root -d jupyter-server /etc/hail/spark_install_hail.sh
Error response from daemon: Container 565fc6b94bb84fa9b26c8679f06ef3d38f63b2a1443e3ef31e17e80afbf82035 is restarting, wait until the container is running
```

We didn't catch this in testing because of https://github.com/DataBiosphere/leonardo/issues/157 -- Leo always uses the `dev` Jupydocker tag, even in a fiab (unless you explicitly change it in a fc-develop branch). So we weren't actually testing the updated Dockerfile; we were testing the dev version with an `ENTRYPOINT`.

This puts back the `ENTRYPOINT` in the Dockerfile, which should fix dev. The drawback is that now pyspark runs before the user script. This might be fine in most cases. If not, we can think later about docker shenanigans to make it happen the other way around.

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by rtitle** [comment]
Note swat's going to fail because it's using the `dev` Jupydocker tag which is broken.

**Comment by rtitle** [comment]
I pushed a `firecloud-develop` branch (with the same name) which changes the Jupydocker image to:
```
dataprocDockerImage = "broadinstitute/leonardo-notebooks:rt-add-back-entrypoint"
```
Now if I understand our automation test infrastructure, this next run should pass.

**Comment by rtitle** [comment]
jenkins retest

**Comment by helgridly** [comment]
I suspect that any user script modifying the Jupyter environment is going to run into trouble. Can we run a placeholder entry point, like bash or something?

**Comment by rtitle** [comment]
Yeah maybe bash would work, will try it

**Comment by rtitle** [comment]
Huh, it still failed with:
```
Error response from daemon: Container 4fdb48e3ba10821430fa518e4250c150320dd88414873789c55586c4e109868f is restarting, wait until the container is running
```
with the bash entrypoint. Investigating...

**Comment by rtitle** [comment]
This latest change seems to work. Checking automation tests to make sure.

**Comment by rtitle** [comment]
Thinking this might be a slightly nicer way of doing this: https://github.com/DataBiosphere/leonardo/pull/187

**Pull request closed without merging**
