### PR TITLE
[CA-914] Point Leo at google projects instead of billing projects

### PR DESCRIPTION
**Pull request by s-rubenstein**
https://broadworkbench.atlassian.net/browse/CA-914

This is intended to point Leonardo at google projects for cluster creation, rather than billing projects.

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by rtitle — APPROVED** [review]
Looks good, I think that change should do it.

Is this change already in Sam prod, for all existing `billing-project` resources? If not, then this PR should wait for the Sam change to be in prod.

Also I think this PR needs to be rebased with `develop` before merge.

**Comment by s-rubenstein** [comment]
I believe it is in prod, but I will definitely make sure before hitting merge.

**Comment by rtitle** [comment]
@s-rubenstein looks like automation tests failed with some 403s during Leo runtime creation: 
```
 java.lang.Exception: message: Failed to create runtime gpalloc-qa-master-pggtdya/automation-test-aifmggqwz, status: 403 Forbidden body: {"causes":[],"exceptionClass":"org.broadinstitute.dsde.workbench.leonardo.http.service.AuthorizationError","message":"ron.weasley@quality.firecloud.org is unauthorized. If you have proper permissions to use the wLeonardoService.scalaorkspace, make sure you are also added to the billing account","source":"leonardo","stackTrace":[],"statusCode":403}
```
https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/31636/

The 403 probably indicates a Sam auth'z error for the project resource. Not sure if this is an issue in test/fiab setup or something else, but something to investigate..

**Review by rtitle — CHANGES_REQUESTED** [review]
requesting changes due to test failures

**Comment by rtitle** [comment]
Are there changes needed to how we request/register gpalloc projects in tests? Our code for that is mostly here: https://github.com/DataBiosphere/leonardo/blob/develop/automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoSuite.scala#L54

**Comment by s-rubenstein** [comment]
@rtitle I can definitely look into that and investigate! There may be! Thank you for pointing me to that code.

**Comment by s-rubenstein** [comment]
Jenkins retest

**Comment by s-rubenstein** [comment]
Jenkins retest

**Comment by s-rubenstein** [comment]
@rtitle tests are now passing!

**Review by rtitle — APPROVED** [review]
:shipit:

**Review by dvoet — APPROVED** [review]

**Review by marctalbott — APPROVED** [review]

**Review by andy7i — APPROVED** [review]
👍

**Pull request merged**
