### PR TITLE
use workbench libs

### PR DESCRIPTION
**Pull request by UrsaStutsman**
\<your comments for this PR go here\>

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by UrsaStutsman** [comment]
@helgridly almost - I'll ping you when it is. (Thought it was yesterday, then uncovered something...)

**Comment by UrsaStutsman** [comment]
@helgridly ready for review! 😄

**Comment by jmthibault79** [comment]
I have not reviewed yet (but I'm excited about this)

Be aware there will be a conflict with #121

**Comment by jmthibault79** [comment]
Missing config?  `java.util.NoSuchElementException: key not found: campaignManagers`

**Comment by jmthibault79** [comment]
I attempted to fix the other config, but then I hit `com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'tempSubjectId'`

**Comment by jmthibault79** [comment]
@helgridly @rtitle moved to #134

**Pull request closed without merging**
