### PR TITLE
[IA-4047] Do not include deleted runtimes when listing resources to delete

### PR DESCRIPTION
**Pull request by LizBaldo**
JIRA ticket: https://broadworkbench.atlassian.net/browse/IA-4047

Fixes a small edge case causing the deleteAllRuntimes endpoint to error out when a workspace only contained deleted runtimes.

### CODE REVIEW

**Review by mlilynolting — APPROVED** [review]

**Review by jdcanas — APPROVED** [review]

**Comment by LizBaldo** [comment]
jenkins retest

**Comment by LizBaldo** [comment]
jenkins retest

**Comment by LizBaldo** [comment]
jenkins retest

**Comment by LizBaldo** [comment]
jenkins retest

**Pull request merged**
