### PR TITLE
AJ-963: Update Cromwell version to 0.2.218

### PR DESCRIPTION
**Pull request by broadbot**
This PR is auto-generated by
[Cromwhelm actions/make_leo_pr](https://github.com/broadinstitute/cromwhelm/blob/main/.github/workflows/make_leo_pr.yml), using
[github actions/github-script](https://github.com/actions/github-script).

It updates cromwell-helm from version 0.2.217 to 0.2.218.

### CODE REVIEW

**Comment by LizBaldo** [comment]
jenkins retest

**Comment by davidangb** [comment]
[org.broadinstitute.dsde.workbench.leonardo.runtimes.RuntimeDataprocSpec.should stop/start a Dataproc cluster with workers and preemptible workers](https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/55004/testReport/org.broadinstitute.dsde.workbench.leonardo.runtimes/RuntimeDataprocSpec/should_stop_start_a_Dataproc_cluster_with_workers_and_preemptible_workers/)
[ Error Details](javascript:hideFailureSummary('id822291-error'))
terra-quality-9a3c5c7b/automation-test-ac2dmh7cz errored due to List(RuntimeError(Failed to create cluster 20 due to io.grpc.StatusRuntimeException: PERMISSION_DENIED: Required 'compute.images.get' permission for 'projects/broad-dsp-gcr-public/global/images/leo-dataproc-image-2-0-51-debian10-2023-03-01-18-47-20',None,2023-04-10T22:41:30Z,Some(TraceId(ee42bbd3a6584ad59314cb649e57ba7c/3939911508519804487))))


Jenkins retest

**Comment by davidangb** [comment]
[org.broadinstitute.dsde.workbench.leonardo.rstudio.RStudioSpec.RStudioSpec environment variables should be available in RStudio](https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/55007/testReport/org.broadinstitute.dsde.workbench.leonardo.rstudio/RStudioSpec/RStudioSpec_environment_variables_should_be_available_in_RStudio/)
[ Error Details](javascript:hideFailureSummary('id822511-error'))
Expected condition failed: waiting for org.broadinstitute.dsde.workbench.service.test.WebBrowserUtil$await$$anon$1@5746036b (tried for 50 second(s) with 500 milliseconds interval) Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03' System info: host: 'd6b964a24159', ip: '172.18.0.8', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.9.1.el7.x86_64', java.version: '17.0.2' Driver info: org.openqa.selenium.remote.RemoteWebDriver Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 83.0.4103.61, chrome: {chromedriverVersion: 83.0.4103.39 (ccbf011cb2d2b..., userDataDir: /tmp/.com.google.Chrome.o0Fy7v}, goog:chromeOptions: {debuggerAddress: localhost:38152}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: 4a7b1a63b2fd6c8dfeff44be945...} Session ID: 4a7b1a63b2fd6c8dfeff44be9450e907

Jenkins retest

**Comment by davidangb** [comment]
[org.broadinstitute.dsde.workbench.leonardo.runtimes.RuntimeDataprocSpec.should stop/start a Dataproc cluster with workers and preemptible workers](https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/55012/testReport/org.broadinstitute.dsde.workbench.leonardo.runtimes/RuntimeDataprocSpec/should_stop_start_a_Dataproc_cluster_with_workers_and_preemptible_workers/)
[ Error Details](javascript:hideFailureSummary('id822581-error'))
terra-quality-e6ad61a7/automation-test-abnigwqbz errored due to List(RuntimeError(Failed to create cluster 14 due to io.grpc.StatusRuntimeException: PERMISSION_DENIED: Required 'compute.images.get' permission for 'projects/broad-dsp-gcr-public/global/images/leo-dataproc-image-2-0-51-debian10-2023-03-01-18-47-20',None,2023-04-11T11:35:59Z,Some(TraceId(ebf0aa18edcf4841bab2af9780557be3/3939911508519804487))))

Jenkins retest

**Comment by LizBaldo** [comment]
@davidangb are you okay with me merging this? The tests failures seem completely unrelated

**Pull request merged**
