### PR TITLE
IA-2534: issue loading genes in IGV Viewer

### PR DESCRIPTION
**Pull request by rtitle**
See explanation in https://broadworkbench.atlassian.net/browse/IA-2534.

I think automation testing would be hard for this, as it involves interacting with the IGV widget. Testing in a fiab.

Test case:
1. Launch runtime with the `gs://rtitle_test/install_igv.sh` user script
2. Open a notebook, run cells:
```
import igv
IGV_Explore = igv.Browser(
  {"genome": "hg19"}  
)
IGV_Explore.show()
```
3. Type "itgam" in the IGV search bar

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by Qi77Qi — APPROVED** [review]
lgtm..just curious, what's in gs://rtitle_test/install_igv.sh?

**Comment by rtitle** [comment]
A user script from a while ago:
```
➜  leonardo git:(rt-fix-igv) gsutil cat gs://rtitle_test/install_igv.sh
#!/bin/bash

JUPYTER_EXTENSION=igv

pip3 install ${JUPYTER_EXTENSION}
sudo -E -u jupyter-user jupyter serverextension enable --py ${JUPYTER_EXTENSION}
sudo -E -u jupyter-user jupyter nbextension install --py ${JUPYTER_EXTENSION} --user
sudo -E -u jupyter-user jupyter nbextension enable --py ${JUPYTER_EXTENSION}
```
I think Comms has something similar. IIRC there were some issues installing `igv` from a notebook…

**Comment by rtitle** [comment]
jenkins retest

**Comment by rtitle** [comment]
It works!
image

**Comment by rtitle** [comment]
@dinvlad @zbedo tagging you on this PR to add 2 urls to Leo `Content-Security-Policy` `connect-src`. My assumption is that this should be ok since these are relatively trusted sites (they support IGV access from a notebook), but let me know.

**Comment by dinvlad** [comment]
Yes, it seems safe enough. Both of those hosts are on-prem at Broad.

**Review by gpcarr — APPROVED** [review]

**Comment by rtitle** [comment]
fiab-start error, jenkins retest

**Comment by rtitle** [comment]
fiab-start having issues, looks like Cromwell not starting up

jenkins retest

**Pull request merged**
