### PR TITLE
[RW-9241] Bump terra-jupyter-aou image to v2.1.14

### PR DESCRIPTION
**Pull request by dmohs**
Docker image changes: https://github.com/DataBiosphere/terra-docker/pull/378
Container images

New disk images:
VM images

### CODE REVIEW

**Review by Qi77Qi — APPROVED** [review]
once tests pass

**Comment by Qi77Qi** [comment]
```
terra-quality-ea71b247/automation-test-abr50xalz errored due to List(RuntimeError(Failed to create cluster 14 due to HTTP connection closed: [https://sam.jenkins-swat-leo-5851.bee.envs-terra.bio:443,None,2022-12-13T21:43:02Z,Some(TraceId(7a689d52673346aaa998e78c11049e1f/3939911508519804487](https://sam.jenkins-swat-leo-5851.bee.envs-terra.bio:443%2Cnone%2C2022-12-13t21:43:02Z,Some(TraceId(7a689d52673346aaa998e78c11049e1f/3939911508519804487)))))
```

jenkins retest

**Comment by Qi77Qi** [comment]
```
[info]   java.lang.RuntimeException: terra-quality-c071aa5f/automation-test-azh8izazz errored due to List(RuntimeError(Jupyter, Welder failed to start after 10 minutes.,None,2022-12-14T00:05:35Z,Some(TraceId(c40a8c31175f4361a9502980707c5101/3939911508519804487))))
```

jenkins retest

**Comment by dmohs** [comment]
```
[info] org.broadinstitute.dsde.workbench.leonardo.notebooks.NotebookGATKSpec *** ABORTED *** (11 minutes, 6 seconds)
[info]   java.lang.RuntimeException: terra-quality-c071aa5f/automation-test-azh8izazz errored due to List(RuntimeError(Jupyter, Welder failed to start after 10 minutes.,None,2022-12-14T00:05:35Z,Some(TraceId(c40a8c31175f4361a9502980707c5101/3939911508519804487))))
```
jenkins retest

**Pull request merged**
