### PR TITLE
[IA-4356] updated version in dataproc image shell script.

### PR DESCRIPTION
**Pull request by n8landolt**
__Jira ticket__: https://broadworkbench.atlassian.net/browse/IA-4356

### What

- DataProc version needs to be updated.

### Why

- Hail / Spark version compatibility.

### What to test

- Create a Hail / Spark cluster on GCP

### Who tested and where

- [ ] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [x] I validated this change in BEE 
- [ ] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

### CODE REVIEW

**Comment by n8landolt** [comment]
jenkins retest

**Comment by n8landolt** [comment]
jenkins retest

**Comment by LizBaldo** [comment]
Have you tested on your BEE and got a successful dataproc cluster creation?

**Comment by n8landolt** [comment]
> Have you tested on your BEE and got a successful dataproc cluster creation?

I have not, Not entirely sure the testing process here. I'll do that now.

**Review by LizBaldo — APPROVED** [review]

**Comment by n8landolt** [comment]
jenkins retest

**Comment by n8landolt** [comment]
jenkins retest

**Comment by n8landolt** [comment]
jenkins retest

**Comment by LizBaldo** [comment]
jenkins retest

**Comment by LizBaldo** [comment]
FYI, I think the automation tests are real failures (not too worried if you could use hail on your BEE, it might just means that the test need some modification like checking for the new hail version?)

**Pull request closed without merging**
