### PR TITLE
Update GKM chart version to 1.2.2

### PR DESCRIPTION
**Pull request by afgane**
Update the GalaxkKubeMan chart to 1.2.2, which includes resource requirement specifications for single-cell tools.

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by Qi77Qi** [comment]
@afgane just curious, will this bump allow us to use more recent gke version too?

**Comment by afgane** [comment]
No, not that. That's still in the works and will come with an upgrade to Galaxy as well. This is just a configuration change for for some single-cell tools needed for a training next week.

**Comment by Qi77Qi** [comment]
replacing this with https://github.com/DataBiosphere/leonardo/pull/2760 since tests won't kick off on this

**Comment by Qi77Qi** [comment]
@afgane talked to DevOps team and they'll add you to databiosphere org, which will hopefully make it so that your future PRs will kick off automation tests properly

**Pull request closed without merging**
