### PR TITLE
IA-3922 merging more integration tests to hopefully reduce flakiness

### PR DESCRIPTION
**Pull request by Qi77Qi**
https://broadworkbench.atlassian.net/browse/IA-3922

* [terra-jupyter-bioconductor today](https://github.com/DataBiosphere/terra-docker/blob/master/terra-jupyter-bioconductor/Dockerfile) is exact the same as `terra-jupyter-r` now, so we don't really need to create a separate runtime with `terra-jupyter-bioconductor` image anymore in tests anymore. So I just moved the same test to the `NotebookRKernelSpec.scala`
* Moved tests in [RStudioDataSyncingSpec.scala](https://github.com/DataBiosphere/leonardo/compare/removeTests?expand=1#diff-1263a9214b19b7e4f9ff9f4d4ae717a6d12def241bb46a2ca34609af7cb0d9d8) to RStudioSpec.scala so that we're re-using the same runtime instead of creating separate runtimes. Side note, it doesn't look like RStudioDataSyncingSpec was running at all

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

[IA-3922]: https://broadworkbench.atlassian.net/browse/IA-3922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by sjacobs146 — APPROVED** [review]
Note that I did not do a thorough review, but since it's tests only I'm feeling safe to approve

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Pull request merged**
