### PR TITLE
IA-3159 remove setting PIP_TARGET

### PR DESCRIPTION
**Pull request by Qi77Qi**
https://broadworkbench.atlassian.net/browse/IA-3159

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by Qi77Qi** [comment]
fiab-start failed...jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Review by kyuksel — APPROVED** [review]
LGTM  👍🏼 

Looks like there's also a related [terra-docker test to uncomment](https://github.com/DataBiosphere/terra-docker/pull/286/files#r781385644) and a [terra-docker issue](https://github.com/DataBiosphere/terra-docker/issues/285) that may be possible to close 😊

**Comment by Qi77Qi** [comment]
@kyuksel  test is already enabled by https://github.com/DataBiosphere/terra-docker/pull/299...  I'll comment on the other issue once the PR is merged

**Pull request merged**
