### PR TITLE
[WM-1467] add automerge workflow

### PR DESCRIPTION
**Pull request by mspector**
This workflow will automatically approve and merge PRs that (1) have passed all checks, and (2) have the label `automerge`. 

This carries out the plan as described in [automated Batch Analysis App rollout](https://docs.google.com/document/d/1eNhGObIvA380uweZO3BkFgE8BbGTUuF6rm1DvflxYVU/edit#heading=h.dil0iv94d0qn). In particular, it will enable automated updates in Leonardo when the CBAS Helm charts are updated.

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by mspector** [comment]
jenkins retest

**Comment by mspector** [comment]
jenkins retest

**Review by kpierre13 — APPROVED** [review]

**Comment by Qi77Qi** [comment]
will this mean that any PR with `automerge` label will be automerged? I just realize leo is a public repo, vs all the devops ones are in private repos

**Comment by mspector** [comment]
@Qi77Qi , yes, as currently implemented it will mean that. let me think about some ways to make this more secure (suggestions welcome!)

**Comment by Qi77Qi** [comment]
@mspector if we can make it so that only PRs from broadbot can be automerged, I think that'll probably suffice...cc @choover-broad for some suggestions

**Comment by mspector** [comment]
@Qi77Qi , I think all of the missing requirements for this PR have been met now. The automerge will only happen when a PR is created by broadbot, and the github action on the cromwhelm side is now successfully passing along the Jira ID in the commit message (see this PR for example: https://github.com/DataBiosphere/leonardo/pull/3012)

Are we good to turn this on?

**Comment by Qi77Qi** [comment]
>I think all of the missing requirements for this PR have been met now. The automerge will only happen when a PR is created by broadbot

that's great! all good from my perspective

Can you check with Ambica to confirm this is good from compliance perspective?

**Comment by mspector** [comment]
jenkins retest

**Comment by mspector** [comment]
jenkins retest

**Comment by mspector** [comment]
@Qi77Qi , just got confirmation from compliance that we are all good!

**Review by Qi77Qi — APPROVED** [review]

**Comment by mspector** [comment]
jenkins retest

**Pull request merged**
