### PR TITLE
[IA-4580] Update Rstudio bioconductor image to 3.17.1

### PR DESCRIPTION
**Pull request by LizBaldo**
__Jira ticket__: https://broadworkbench.atlassian.net/browse/IA-4580

## Summary of changes

Leo follow up from Bioconductor PR in terra-docker: https://github.com/DataBiosphere/terra-docker/pull/458/files

### What to test

Just tested on my BEE and created and RSTudio runtime with the following request:
```
{
  "runtimeConfig": {
    "cloudService": "gce",
    "machineType": "n1-standard-4",
    "diskSize": 100
  },
  "toolDockerImage": "us.gcr.io/broad-dsp-gcr-public/anvil-rstudio-bioconductor:3.17.1"
}
```

The runtime was running and i could access the RStudio URL fine 👍  So I am going to merge this to Dev ASAP and then will promote the UI change to prod on Thursday morning to sync with the monolith release

### Who tested and where

- [ ] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [ ] I validated this change 
- [ ] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

### CODE REVIEW

**Review by lucymcnatt — APPROVED** [review]

**Comment by LizBaldo** [comment]
jenkins retest

**Comment by LizBaldo** [comment]
jenkins retest

**Comment by lucymcnatt** [comment]
jenkins retest

**Comment by LizBaldo** [comment]
jenkins retest

**Pull request merged**
