### PR TITLE
[QA-1514] attempt fix

### PR DESCRIPTION
**Pull request by jdcanas**

### CODE REVIEW

**Comment by jdcanas** [comment]
multi-test

**Comment by jdcanas** [comment]
multi-test

**Comment by jdcanas** [comment]
jenkins retest - automation failures in unrelated specs

**Review by Qi77Qi — APPROVED** [review]
lgtm...I think this should be fine...basically we're validating that workspace name will always be the parent dir, which is what the jupyter image is setting the `WORKSPACE_NAME` env to

**Pull request merged**
