### PR TITLE
Don't caps-lock Playground Mode

### PR DESCRIPTION
**Pull request by calbach**
This makes it consistent with edit mode.

Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by rtitle — APPROVED** [review]
LOOKS GOOD TO ME

**Comment by rtitle** [comment]
jenkins retest

**Comment by rtitle** [comment]
I just merged a PR to refactor/improve a bunch of automation tests -- you may want to rebase this branch to improve the likelihood of a green build.

**Comment by calbach** [comment]
:(

**Comment by calbach** [comment]
jenkins retest

**Pull request merged**
