### PR TITLE
[IA-1556] listClusters should reflect installed tool

### PR DESCRIPTION
**Pull request by rtitle**
https://broadworkbench.atlassian.net/browse/IA-1556

This PR does the following:
1. Sets a `tool` label on the cluster when it is created, which can either be `Jupyter` or `RStudio`. The label is returned in either `getCluster` or `listCluster` responses.
2. Ensures the `clusterUrl` field is correct in both `getCluster` and `listCluster` responses.

@zarsky-broad does the above work for you? (I'm working on the other issues you reported as well.) 

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by zarsky-broad** [comment]
Excellent.

**Comment by akarukappadath** [comment]
Terra goes by '1 tool per cluster', but does AoU also follow this? Is this something we want to bake into Leo?

**Comment by rtitle** [comment]
@akarukappadath that's a good question. I think it's ok to bake "1 tool per cluster" into Leo. There's been no product ask for multi-tools per cluster, and in some sense we've _already_ baked this into Leo with the `toolDockerImage` and `clusterUrl` parameters. I think we'll probably want to start supporting >1 tools per cluster when we do k8s, but that will involve a lot of other work too.

**Review by Qi77Qi — APPROVED** [review]
My only concern is it's not clear to me if clusterImage belong in listCluster. In general, it's not clear to me which fields belong in listCluster API vs getCluster...it seems we just add fields as demand arises, which doesn't seem desirable to me.

**Comment by rtitle** [comment]
Thanks.. yeah we could use requirements about what belongs in listCluster or not. Currently my rule of thumb is that `listCluster` does not join to _any_ tables, except labels. But that's not a firm requirement.

**Comment by Qi77Qi** [comment]
@rtitle I think that rule sounds good to me

**Pull request merged**
