### PR TITLE
Fixed compilation errors from merge conflict

### PR DESCRIPTION
**Pull request by akarukappadath**
There were some compilation errors that arose from my last PR (https://github.com/DataBiosphere/leonardo/commit/f69247377be78566860942d15d11558543e634e9), probably from a merge conflict. This PR fixes those issues.

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by akarukappadath** [comment]
jenkins retest

**Comment by rtitle** [comment]
Looks like there are some test compilation errors too. Use `sbt test:compile` to catch those.

**Comment by rtitle** [comment]
Also check `sbt compile` and `sbt test:compile` in the automation directory.

**Comment by rtitle** [comment]
I went ahead and merged this :)

**Pull request merged**
