### PR TITLE
Rl version endpoint databiosphere

### PR DESCRIPTION
**Pull request by RLuckom**
Redux of https://github.com/DataBiosphere/leonardo/pull/708

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by RLuckom** [comment]
@rtitle good news / bad news situation. In response to your comment on the previous PR, the version string is _not_ available in the test, so I updated the test to look for the string `"n/a"`. I did verify that it works in a fiab--you can see it in action with `curl -k https://35.192.224.241:30443/version` while from a connection that can reach the fiabs.

**Review by rtitle — APPROVED** [review]
Cool, works for me 👍

**Comment by rtitle** [comment]
Tests failed with most likely a transient error. jenkins retest anyway

**Comment by rtitle** [comment]
Tests failed with most likely a transient error. jenkins retest anyway

**Comment by rtitle** [comment]
Tests failed with most likely a transient error. jenkins retest anyway

**Pull request merged**
