### PR TITLE
[RW-7478][risk=no]Bump the cached AoU docker image version. 

### PR DESCRIPTION
**Pull request by yonghaoy**
\<your comments for this PR go here\>

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by Qi77Qi** [comment]
thanks @yonghaoy for remembering to update this! 
There's actually one more reference. https://github.com/DataBiosphere/leonardo/blob/develop/jenkins/dataproc-custom-images/prepare-custom-leonardo-jupyter-dataproc-image.sh

I'm also working on updating cached latest version for all images [here](https://github.com/DataBiosphere/leonardo/pull/2347)...so I can just update that PR's old aou version to 2.0.2 as well

**Comment by yonghaoy** [comment]
> thanks @yonghaoy for remembering to update this! There's actually one more reference. https://github.com/DataBiosphere/leonardo/blob/develop/jenkins/dataproc-custom-images/prepare-custom-leonardo-jupyter-dataproc-image.sh
> 
> I'm also working on updating cached latest version for all images [here](https://github.com/DataBiosphere/leonardo/pull/2347)...so I can just update that PR's old aou version to 2.0.2 as well

Thanks! I heard there were some automated tools that can do this, and was wondering why it's not working. Then I will close mine.

**Comment by Qi77Qi** [comment]
@yonghaoy the automation doesn't update the old image reference. it only updates the latest...so my question to you is, do you intend to update old reference to 2.0.2? is that in prod for AoU today?

**Comment by yonghaoy** [comment]
> @yonghaoy the automation doesn't update the old image reference. it only updates the latest...so my question to you is, do you intend to update old reference to 2.0.2? is that in prod for AoU today?

@Qi77Qi In prod is 2.0.1. I don't think we want 2.0.2 as it caused issues then we rolled it back. 
Sorry for the confusion,  what you want me to do next? Reopen this PR and also update prepare-custom-leonardo-jupyter-dataproc-image.sh?  OR your IA-2992 PR takes care everything?

**Comment by Qi77Qi** [comment]
@yonghaoy ok...the old reference is for for what's in prod...so I'll leave it as `2.0.1` then...

> what you want me to do next? Reopen this PR and also update prepare-custom-leonardo-jupyter-dataproc-image.sh? OR your IA-2992 PR takes care everything?

Nothing at this point

**Pull request closed without merging**
