### PR TITLE
WX-1369 Enable updating of Workflows App, Cromwell Runner App

### PR DESCRIPTION
**Pull request by jgainerdewar**
__Jira ticket__: https://broadworkbench.atlassian.net/browse/WX-1369

## Summary of changes

Attempting to update CROMWELL_RUNNER_APP and WORKFLOWS_APP left the app in a permanent UPDATING state because a match statement in `LeoPubsubMessageSubscriber` was never updated to account for the new app types. This PR updates the logic in `LeoPubsubMessageSubscriber` to use the same method as front Leo for mapping an app type and cloud to that app's config. Keeping this logic in a single place will help prevent this type of error in the future.

### What to test

- 

### Who tested and where

I tested in a BEE and successfully upgraded both apps. Also tested upgrading CROMWELL to ensure that still worked.

- [ ] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [x] I validated this change 
- [ ] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

### CODE REVIEW

**Comment by jgainerdewar** [comment]
jenkins retest

**Review by LizBaldo — APPROVED** [review]
About to run offline so I could only take a quick glance but that makes a lot of sense to me :)
I am assuming that the logic is already covered by unit tests if it is already used by front leo?

👍 because I will be OOO next week and I don't want to block you :) But if @Qi77Qi can take a look and is okay with it, :shipit:

**Review by Qi77Qi — APPROVED** [review]
RStudio app is tested in automation tests...we're good as long as automation tests pass :)

**Comment by jgainerdewar** [comment]
jenkins retest

**Comment by jgainerdewar** [comment]
jenkins retest

**Comment by jgainerdewar** [comment]
jenkins retest

**Comment by jgainerdewar** [comment]
jenkins retest

**Pull request merged**
