### PR TITLE
Jr build efficiency fix - skip tests

### PR DESCRIPTION
**Pull request by jacmrob**
\<your comments for this PR go here\>

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by jacmrob** [comment]
ok i will restore that variable

**Comment by jacmrob** [comment]
ok i restored the `DOCKER_TAG` var and defaulted it to the git hash, and then also tagged all images with git branch, so all images will have 2 tags - whatever `DOCKER_TAG` is (in our case, git hash), and `GIT_BRANCH`

**Comment by eap** [comment]
Thanks for doing this. LGTM

**Comment by jacmrob** [comment]
tested - https://fc-jenkins.dsp-techops.broadinstitute.org/view/Build/job/leonardo-build/2588/

**Pull request merged**
