### PR TITLE
[IA-3397] Update terra-jupyter r and bioc and anvil rstudio images

### PR DESCRIPTION
**Pull request by gpcarr**
integrates these docker PRs: https://github.com/DataBiosphere/terra-docker/pull/320
https://github.com/DataBiosphere/terra-docker/pull/319

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by Qi77Qi — APPROVED** [review]
once tests pass

**Comment by gpcarr** [comment]
jenkins retest

**Comment by gpcarr** [comment]
jenkins retest - there were no actual failures https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/47809/

**Comment by gpcarr** [comment]
jenkins retest - fiab start failure

**Comment by gpcarr** [comment]
jenkins retest

**Comment by gpcarr** [comment]
jenkins retest

**Comment by gpcarr** [comment]
jenkins retest - fiab start failure

**Comment by gpcarr** [comment]
jenkins retest

**Comment by gpcarr** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by gpcarr** [comment]
jenkins retest

**Comment by gpcarr** [comment]
unrelated failure - jenkins retest

**Comment by gpcarr** [comment]
jenkins retest

**Comment by gpcarr** [comment]
jenkins retest

**Comment by gpcarr** [comment]
unrelated test failure - jenkins retest

**Comment by Qi77Qi** [comment]
```
[info] org.broadinstitute.dsde.workbench.leonardo.notebooks.NotebookAouSpec *** ABORTED *** (11 minutes, 1 second)
[info]   java.lang.RuntimeException: terra-quality-22531efc/automation-test-adnvsuowz errored due to List(RuntimeError(Jupyter, Welder failed to start after 10 minutes.,None,2022-05-17T16:09:36Z,None))
[info]   at org.broadinstitute.dsde.workbench.leonardo.LeonardoApiClient$.$anonfun$waitUntilRunning$2(LeonardoApiClient.scala:250)
[info]   at map @ org.broadinstitute.dsde.workbench.leonardo.LeonardoApiClient$.$anonfun$waitUntilRunning$2(LeonardoApiClient.scala:246)
[info]   at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
[info]   at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
[info]   at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
[info]   at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
[info]   at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
[info]   at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
[info]   at modify @ fs2.internal.Scope.close(Scope.scala:262)
[info]   at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
[info]   at rethrow$extension @ fs2.Compiler$Target.$anonfun$compile$1(Compiler.scala:156)
[info]   at get @ fs2.internal.Scope.openScope(Scope.scala:281)
[info]   at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
[info]   at flatMap @ fs2.Pull$.$anonfun$compile$21(Pull.scala:1185)
[info]   at update @ fs2.internal.Scope.releaseChildScope(Scope.scala:224)
[info]   at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
```

we might have some real issue for AoU image...

**Pull request merged**
