### PR TITLE
QA-1385: Adding pausing

### PR DESCRIPTION
**Pull request by xuscrbw**
It looks like the await condition is not enough. Going to try adding a pause here. Not the most elegant solution.

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by xuscrbw** [comment]
jenkins retest

**Comment by xuscrbw** [comment]
jenkins retest

**Comment by xuscrbw** [comment]
jenkins retest

**Comment by xuscrbw** [comment]
jenkins retest

**Comment by rtitle** [comment]
I just got an RShiny test failure in my PR.. does this help things @xuscrbw ? Should this be merged?

jenkins retest

**Review by rtitle — APPROVED** [review]

**Comment by xuscrbw** [comment]
I think we can try so see if this works. Looking at the failure screenshots, it is still selecting the a() autocomplete option. This pause might help us catch it happening. Will merge this once this passes

**Pull request merged**
