### PR TITLE
[IA-4485] Tag AzureRuntimeSpec as ExcludeFromJenkins

### PR DESCRIPTION
**Pull request by mlilynolting**
Group LeonardoTags into a wrapper object, move them into the generic package instead of `db`, and add `ExcludeFromJenkins`. With https://github.com/broadinstitute/firecloud-automated-testing/pull/157/files, this will tell Jenkins Swatomation test runs to ignore the new tests which are configured to run as Github Actions.

__Jira ticket__: https://broadworkbench.atlassian.net/browse/IA-4485

### What to test

- [x] Open this PR, triggering Swat run Swat1
- [x] Swat1 fails on AzureRuntimeSpec
- [x] Manually retrigger Swat run Swat2 using Jenkins "Edit parameters and rerun" command. For TEST_ENTRYPOINT enter `testOnly -- -l ProdTest -l NotebooksCanaryTest -l ExcludeFromJenkins`
- [x] Swat2 does not run AzureRuntimeSpec and does not fail because of it

### Who tested and where

- [ ] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [ ] I validated this change 
- [ ] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

### CODE REVIEW

**Comment by mlilynolting** [comment]
jenkins retest

**Comment by mlilynolting** [comment]
Test: Swat1 failed on AzureRuntimeSpec. https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/56696/testReport/org.broadinstitute.dsde.workbench.leonardo.azure/AzureRuntimeSpec/create__get__delete_azure_runtime/

**Comment by mlilynolting** [comment]
Temporarily configured [leonardo-fiab-test-runner](https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner) with TEST_ENTRYPOINT `testOnly -- -l ProdTest -l NotebooksCanaryTest -l ExcludeFromJenkins`

Swat2 failed (but not on AzureRuntimeSpec!) https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/56701/

The console output repeats `AzureRuntimeSpec:` on an otherwise blank line twice, but does not appear to run the test within.

@jdcanas I think that `@DoNotDiscover` should be restored on `AzureRuntimeSpec` (or possibly `LeonardoAzureSuite` if suites can be annotated), and `automation_test.yml` should probably be running
```
leo_test_command: "testOnly -s org.broadinstitute.dsde.workbench.leonardo.LeonardoAzureSuite"
```

But that is out of scope for this fix.

**Review by LizBaldo — APPROVED** [review]
Thanks for working through this and figuring out a fix :)

**Comment by mlilynolting** [comment]
Merged change to firecloud-automated-testing/run-automation-tests.sh, which should cause the tagged AzureRuntimeSpec to be automatically excluded from swatomation runs on Jenkins (without affecting runs triggered thru Github Action, which use a different flow).

Await the completion of https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline-leo/10124/ (without AzureRuntimeSpec error) to verify.

**Comment by mlilynolting** [comment]
jenkins retest

**Comment by mlilynolting** [comment]
Realized that the default value in `run-automation-tests.sh` is never hit because a default is also defined in leonardo-fiab-test-runner Jenkins job. Removed that default (via Jenkins > job > Configure) and rerunning.

**Comment by mlilynolting** [comment]
jenkins retest

**Comment by mlilynolting** [comment]
Eventually got a swat run demonstrating that ExcludeFromJenkins is being honored: https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/56720/consoleFull

**Pull request merged**
