### PR TITLE
Update GKM to 2.8.1

### PR DESCRIPTION
**Pull request by afgane**
This updates Galaxykubemac chart to v2.8.1 that fixes a path to the CSS for the welcome page in Galaxy (https://github.com/galaxyproject/galaxykubeman-helm/pull/76).

### CODE REVIEW

**Review by lucymcnatt — APPROVED** [review]

**Comment by lucymcnatt** [comment]
Looks good, tested on my BEE

**Comment by lucymcnatt** [comment]
jenkins retest

**Comment by lucymcnatt** [comment]
Do you need anything else to merge this in?

**Comment by afgane** [comment]
Nothing else needed - ready for merging.

**Pull request merged**
