### PR TITLE
[IA-4116] Set serviceAccount.name for custom APP.

### PR DESCRIPTION
**Pull request by yonghaoy**
[serviceAccount.name](https://github.com/DataBiosphere/terra-app/blob/main/terra-app-chart/values.yaml#L26)
is needed to make workload identity work. Currently it is missing in custom APP. 

I verified by manually set this field in GKE console, and verified `gsutil` command works

Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by rtitle — APPROVED** [review]
Cool - that matches what I was thinking. 👍 

:shipit: if tests pass

**Comment by yonghaoy** [comment]
Jenkins retest

**Comment by yonghaoy** [comment]
@rtitle  codecov/patch fails, but I think that is because I reformat that file. I added a unit test which suppose to increase test coverage. Shall I go ahead and merge this PR or I should revert my `sbt scalaFormatAll` change?

**Comment by rtitle** [comment]
@yonghaoy `codecov` shouldn't block merge. Looks like the tests were successful. I'll merge this.

**Pull request merged**
