### PR TITLE
upgrade Docker version to 18.06.2

### PR DESCRIPTION
**Pull request by MatthewBemis**
this is a more minor upgrade that still addresses the vulnerability according to https://docs.docker.com/engine/release-notes/#18062

Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by rtitle** [comment]
Looks good, if tests pass. Do we need to patch all existing clusters by triggering a cluster creation? I think Saturn and AoU have mechanisms to do that -- check with those teams.

**Comment by MatthewBemis** [comment]
jenkins retest - something caused the kernel to die in one test. i don't think it's related to this PR

**Comment by MatthewBemis** [comment]
jenkins retest - all 4 failures were the result of a timeout claiming a gpalloc project

**Comment by MatthewBemis** [comment]
i am prepping another jenkins retest but i am going to look further into the most recent failure

**Comment by MatthewBemis** [comment]
@rtitle i am emailing the TLs for those two teams to see if they have a good way to handle it. we'll need to take care of FC also

**Review by rtitle — APPROVED** [review]

**Pull request merged**
