### PR TITLE
[IA-4857] Security update: jose4j 0.9.3 to 0.9.4

### PR DESCRIPTION
**Pull request by lucymcnatt**
__Jira ticket__: https://broadworkbench.atlassian.net/browse/[ticket_number]

### What

- Updating the dependency jose4j to 0.9.4 due to a security vulnerability in 0.9.3
- Because this requires updating wblibs, had to bring in a new google2 version that includes [these changes](https://github.com/broadinstitute/workbench-libs/pull/1646/files#diff-548289fa7f24197845d4a242fc36cfd7042871d9563dd7f59ed94e16de5a01b2) to make the pubsub cloud-agnostic

### Why

-

### What to test

- 

### Who tested and where

- [ ] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [ ] I validated this change 
- [ ] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

### CODE REVIEW

**Review by LizBaldo — APPROVED** [review]
LGTM! One question though would be to also double check workbench-libs, it might also be on the wrong version

**Comment by LizBaldo** [comment]
It might be safer to close this and open a new PR to just do the dependencies update instead of resolving the merge conflicts

**Comment by lucymcnatt** [comment]
> It might be safer to close this and open a new PR to just do the dependencies update instead of resolving the merge conflicts

yeahhh let me do a cherry-pick to get back to the original changes

**Comment by LizBaldo** [comment]
Shoot, sorry I just opened this one https://github.com/DataBiosphere/leonardo/pull/4387

**Comment by lucymcnatt** [comment]
lol no worries! I'll take a look at that one

**Comment by LizBaldo** [comment]
Thank you! I think it might be safer to close this one, sorry for the back and forth 🙈

**Pull request closed without merging**
