### PR TITLE
[no ticket] validate DiskName

### PR DESCRIPTION
**Pull request by Qi77Qi**
\<your comments for this PR go here\>

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by rtitle — APPROVED** [review]
Looks good.. so by putting the validation in the `DiskName` decoder it handles both `createRuntime` and `createDisk` cases.

**Comment by rtitle** [comment]
btw good find @xuscrbw :)

**Comment by Qi77Qi** [comment]
weird mysql didn't start error. jenkins restart

**Comment by Qi77Qi** [comment]
same mysql connection error....jenkins retest

**Comment by rtitle** [comment]
jenkins retest

**Pull request merged**
