### PR TITLE
[IA-4452] Infer cloudProvider from cloudContext and include it in DB …

### PR DESCRIPTION
**Pull request by mlilynolting**
…cluster queries to leverage the unique key index

__Jira ticket__: https://broadworkbench.atlassian.net/browse/[ticket_number]

### What

-

### Why

-

### What to test

- 

### Who tested and where

- [ ] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [ ] I validated this change 
- [ ] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

### CODE REVIEW

**Comment by mlilynolting** [comment]
jenkins retest

**Comment by mlilynolting** [comment]
Cleanish swat run: Welder failed to start. https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/56426/

**Comment by mlilynolting** [comment]
jenkins retest

**Comment by mlilynolting** [comment]
jenkins retest

**Review by Qi77Qi — APPROVED** [review]

**Comment by mlilynolting** [comment]
Closing in favor of https://github.com/DataBiosphere/leonardo/actions/runs/5671305365/job/15368152102?pr=3519 which combines 2 related PRs.

**Pull request closed without merging**
