### PR TITLE
IA-3656 Update GKM to 2.1.0

### PR DESCRIPTION
**Pull request by afgane**
Update GKM to v2.0.0 that is uses `5.0.0-anvil.1` of the Galaxy chart and is compatible with K8s 1.22-1.24. 

This is likely to require #2802 (or some version of it) because variables referencing CVMFS are no longer available in this version of GKM.  

This PR doesn't remove CVMFS pvcIds from DB. Will drop that once we've confirmed things work as expected

### CODE REVIEW

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest...fiab-start failure

**Comment by afgane** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
see if updating nginx chart version helps

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
fiab-start failure...jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
fiab-start failure...jenkins retest

**Comment by Qi77Qi** [comment]
```
      org.broadinstitute.dsde.workbench.leonardo.RestError: message: Failed to create runtime terra-quality-c72e98ca/automation-test-azpyeqyrz, status: 400 Bad Request body: {"source":"leonardo","message":"AuthProvider error: {\"causes\":[],\"message\":\"Project terra-quality-c72e98ca must be in Terra Organization\",\"source\":\"sam\",\"stackTrace\":[],\"statusCode\":400}","statusCode":400,"exceptionClass":"class org.broadinstitute.dsde.workbench.leonardo.dao.AuthProviderException","traceId":"a509160e2b144bdb8c2d1999953aea0a/3939911508519804487"}
```

jenkins retest

**Comment by Qi77Qi** [comment]
```
message: Failed to create runtime terra-quality-d72fd4b6/automation-test-ahjlqdljz, status: 400 Bad Request body: {"source":"leonardo","message":"AuthProvider error: {\"causes\":[],\"message\":\"Project terra-quality-d72fd4b6 must be in Terra Organization\",\"source\":\"sam\",\"stackTrace\":[],\"statusCode\":400}","statusCode":400,"exceptionClass":"class org.broadinstitute.dsde.workbench.leonardo.dao.AuthProviderException","traceId":"daba01cb51da4963a252bb13c8d1b3e1/3939911508519804487"}
```

again...jenkins retest

**Comment by Qi77Qi** [comment]
the project issue is fixed... jenkins retest

**Review by LizBaldo — APPROVED** [review]
Tested in the BEE environment and was able to launch. pause, resume and delete a galaxy app. The data upload does not work as the URL for the BEE qa environment is not in the CSP allowlist as expected.

**Comment by LizBaldo** [comment]
jenkins retest

**Comment by LizBaldo** [comment]
jenkins retest

**Pull request merged**
