### PR TITLE
QA-1205 :  Creating more responsive ways to deal with second modal

### PR DESCRIPTION
**Pull request by xuscrbw**
We are still running into issues with having the second modal appear. I'm not super certain if this is because we are clicking before the modal shows up, or if there's another issue.

Going to try this new approach which will wait until a second modal appears. Once it appears, it'll perform a click. I don't think we should ever run into having 3 modals at the same time.

This fix might not work for GCE, so leaving that to be fixed with Qi's PR
---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by xuscrbw** [comment]
jenkins retest

**Comment by xuscrbw** [comment]
jenkins retest

**Comment by xuscrbw** [comment]
jenkins retest

**Comment by xuscrbw** [comment]
jenkins retest

**Comment by xuscrbw** [comment]
jenkins retest

**Comment by xuscrbw** [comment]
jenkins retest

**Review by rtitle — APPROVED** [review]
LGTM if tests pass

**Pull request merged**
