### PR TITLE
Make terra remote file source writeable in Galaxy

### PR DESCRIPTION
**Pull request by almahmoud**
Friends with https://github.com/galaxyproject/galaxykubeman-helm/pull/31

- [x] Test this change deployed correctly and works on dev environment after deployment

Change was added to chart, but also needed here in order not to overwrite it

### CODE REVIEW

**Comment by Qi77Qi** [comment]
will this require a galaxy chart version upgrade?

**Comment by almahmoud** [comment]
It works independent of it, but yes it's meant to go with the new GKM version that will have Galaxy `21.05`.

**Review by Qi77Qi — APPROVED** [review]
can you add a comment next to this line about this is available since galaxy 21.05...

approving assuming there will be a followup PR bumping the chart version

**Comment by rtitle** [comment]
Closing in favor of https://github.com/DataBiosphere/leonardo/pull/2187

**Pull request closed without merging**
