### PR TITLE
[WOR-1056] Remove breaking & unnecessary LZ resource fields

### PR DESCRIPTION
**Pull request by aherbst-broad**
__Jira ticket__: **https://broadworkbench.atlassian.net/browse/WOR-1056**

### What

- Leo chokes on the new resources being returned from the LZS. It seems these are unused at the moment, so they will be excluded until we can find a saner way to include these. 

### Why

-

### What to test

- 

### Who tested and where

- [ ] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [ ] I validated this change 
- [ ] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

### CODE REVIEW

**Review by LizBaldo — APPROVED** [review]

**Comment by aherbst-broad** [comment]
jenkins retest

**Comment by aherbst-broad** [comment]
jenkins retest

**Review by rtitle — APPROVED** [review]
Looks good, thanks for fixing this

**Comment by aherbst-broad** [comment]
jenkins retest

**Comment by aherbst-broad** [comment]
jenkins retest

**Comment by aherbst-broad** [comment]
jenkins retest

**Comment by aherbst-broad** [comment]
jenkins retest

**Pull request merged**
