### PR TITLE
Update GalaxyKubeman chart to version 2.8.0

### PR DESCRIPTION
**Pull request by ksuderman**
## Summary of changes

Update the GalaxyKubeman chart to 2.8.0 which uses Galaxy 23.1 **NOTE** Galaxy 23.1 requires Kubernetes 1.25 and does not work correctly with 1.26.

### Who tested and where

- [ ] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [ ] I validated this change 
- [ ] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

### CODE REVIEW

**Comment by LizBaldo** [comment]
@ksuderman, is this ready to be reviewed by IA? Happy to help push the testing / merge.

**Review by afgane — APPROVED** [review]
lgtm

**Comment by ksuderman** [comment]
> @ksuderman, is this ready to be reviewed by IA? Happy to help push the testing / merge.

Yes it should be ready to go.  There are only a few minor version updates.

**Comment by lucymcnatt** [comment]
Do you need anything else to merge this? Or is it ready to go?

**Comment by ksuderman** [comment]
Closing in favor of https://github.com/DataBiosphere/leonardo/pull/3924

**Pull request closed without merging**
