### PR TITLE
[RW-9296] Update terra-jupyter-aou version to 2.1.15 in GCE image

### PR DESCRIPTION
**Pull request by dmohs**
This should have been part of previous PR:
https://github.com/DataBiosphere/leonardo/pull/3073

```
% gcloud container images list-tags us.gcr.io/broad-dsp-gcr-public/terra-jupyter-aou | head -n 3
DIGEST        TAGS                   TIMESTAMP
473700884963  2.1.15                 2022-12-16T10:27:17
9fe2e3d89189  2.1.14                 2022-12-12T16:07:49
```

```
% gcloud compute images list --project=broad-dsp-gcr-public --filter='name~^custom-leo' --sort-by=~creationTimestamp --limit=3
NAME                                                 PROJECT               FAMILY                 DEPRECATED  STATUS
custom-leo-2-image-dataproc-2-0-51-debian10-8e87ddc  broad-dsp-gcr-public  dataproc-custom-image              READY
custom-leo-2-gce-cos-image-8e87ddc                   broad-dsp-gcr-public  gce-custom-image                   READY
custom-leo-image-dataproc-2-0-51-debian10-8e87ddc-2  broad-dsp-gcr-public  dataproc-custom-image              READY
```

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by Qi77Qi — COMMENTED** [review]
ah...so i think for this, u just need to regenerate the custom image for GCE then

**Comment by dmohs** [comment]
Thank you, Qi. Done, I believe.

**Review by Qi77Qi — APPROVED** [review]

**Comment by dmohs** [comment]
```
15:53:01 8:53PM INF rawls:            error error="timed out waiting for healthy (Degraded: rawls-backend-deployment: MountVolume.SetUp failed for volume \"honeycomb-cert-mount\" : secret \"honeycomb-cert\" not found)" status="Degraded: rawls-backend-deployment: MountVolume.SetUp failed for volume \"honeycomb-cert-mount\" : secret \"honeycomb-cert\" not found" t=32m15s
```

**Comment by dmohs** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by dmohs** [comment]
```
16:49:37 9:49PM INF ontology:         error error="timed out waiting for healthy (Degraded: ontology-deployment: MountVolume.SetUp failed for volume \"honeycomb-cert-mount\" : secret \"honeycomb-cert\" not found)" status="Degraded: ontology-deployment: MountVolume.SetUp failed for volume \"honeycomb-cert-mount\" : secret \"honeycomb-cert\" not found" t=30m41s
```

**Comment by dmohs** [comment]
jenkins retest

**Comment by dmohs** [comment]
```
[info] - should stop/start a Dataproc cluster with workers and preemptible workers *** FAILED *** (1 hour, 1 minute, 9 seconds)
[info]   java.lang.RuntimeException: terra-quality-4d92c249/automation-test-al2qrwsgz errored due to List(RuntimeError(Required 'compute.images.get' permission for 'projects/broad-dsp-gcr-public/global/images/custom-leo-image-dataproc-2-0-51-debian10-a46b242',Some(7),2022-12-21T16:05:34Z,Some(TraceId(449fe95a597440ebafe414d83525345e/3939911508519804487))))
```

**Comment by dmohs** [comment]
https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/53595/console
```
Build timed out (after 120 minutes). Marking the build as aborted.
```
jenkins retest

**Comment by dmohs** [comment]
jenkins retest

**Comment by dmohs** [comment]
https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/53607/console
```
00:39:20 [io-compute-6                            ] INFO  [o.h.c.middleware.Retry   :$anonfun$create$5] - Request method=GET uri=https://leonardo.jenkins-swat-leo-6070.bee.envs-terra.bio/api/google/v1/runtimes/terra-quality-b27d23db/automation-test-aisyvcesz headers=Authorization: <REDACTED>,X-Cloud-Trace-Context: 1170c679e8f94479b56a9564320b32aa/3939911508519804487,Accept: application/json has failed on attempt #5 with reason 503 Service Unavailable. Retrying after 23221 milliseconds.
00:39:43 [io-compute-0                            ] INFO  [o.h.c.m.ResponseLogger   :$anonfun$defaultLogAction$1] - HTTP/1.1 503 Service Unavailable Headers(Date: Thu, 22 Dec 2022 00:39:43 GMT, Content-Type: text/html, Content-Length: 190, Connection: keep-alive, Strict-Transport-Security: max-age=15724800; includeSubDomains) body="<html>

<head><title>503 Service Temporarily Unavailable</title></head>

<body>

<center><h1>503 Service Temporarily Unavailable</h1></center>

<hr><center>nginx</center>

</body>

</html>

"
00:39:44 [io-compute-0                            ] INFO  [o.h.b.client.PoolManager :$anonfun$shutdown$2] - Shutting down connection pool: curAllocated=1 idleQueues.size=1 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
[info] - Patch endpoint should perform a stop/start transition for Dataproc cluster *** FAILED *** (55 minutes, 31 seconds)
[info]   java.util.concurrent.TimeoutException: create runtime terra-quality-b27d23db/automation-test-ask5malqz. Runtime is still in Creating
[info]   at org.broadinstitute.dsde.workbench.leonardo.LeonardoApiClient$.$anonfun$waitUntilRunning$2(LeonardoApiClient.scala:261)
```

**Comment by dmohs** [comment]
jenkins retest

**Comment by dmohs** [comment]
https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/53611/consoleText
```
[info] - should create a Dataproc cluster with workers and preemptible workers *** FAILED *** (3 minutes, 5 seconds)
[info]   java.lang.RuntimeException: terra-quality-b613a314/automation-test-azycfl87z errored due to List(RuntimeError(Required 'compute.images.get' permission for 'projects/broad-dsp-gcr-public/global/images/custom-leo-image-dataproc-2-0-51-debian10-a46b242',Some(7),2022-12-22T14:34:03Z,Some(TraceId(c987d982a55a48a4a7561116b688d581/3939911508519804487))))
```
jenkins retest

**Comment by dmohs** [comment]
https://fc-jenkins.dsp-techops.broadinstitute.org/job/fiab-start/88235/console
```
13:22:01 6:22PM INF ontology:         error error="timed out waiting for healthy (Degraded: ontology-deployment: MountVolume.SetUp failed for volume \"honeycomb-cert-mount\" : secret \"honeycomb-cert\" not found)" status="Degraded: ontology-deployment: MountVolume.SetUp failed for volume \"honeycomb-cert-mount\" : secret \"honeycomb-cert\" not found" t=30m11s
```
jenkins retest

**Pull request merged**
