### PR TITLE
Update azure_vm_init_script.sh

### PR DESCRIPTION
**Pull request by erdalcosgun**
__Jira ticket__: https://broadworkbench.atlassian.net/browse/IA-4521

## Summary of changes

Test the automated updates on R and  docker group changes.
### What

-

### Why

-

### What to test

- 

### Who tested and where

- [ ] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [ ] I validated this change 
- [ ] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

### CODE REVIEW

**Comment by erdalcosgun** [comment]
jenkins retest

**Comment by LizBaldo** [comment]
@erdalcosgun  thanks  for taking a stab at it, we should check in with App Sec first though to make sure they are on board with creating that group

**Comment by erdalcosgun** [comment]
jenkins retest

**Comment by erdalcosgun** [comment]
jenkins retest

**Comment by erdalcosgun** [comment]
jenkins retest

**Pull request closed without merging**
