### PR TITLE
RW-10503 Add AoU SAS chart version 0.1.0

### PR DESCRIPTION
**Pull request by jmthibault79**
__Jira ticket__: https://precisionmedicineinitiative.atlassian.net/browse/RW-10503

### What

- Adding SAS chart in leo image

### Why

- Supporting SAS

### What to test

- 

### Who tested and where

- [ ] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [x] I validated this change 
- [x] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

### CODE REVIEW

**Review by Qi77Qi — APPROVED** [review]
we did this during mobbing and verified that the chart is added properly 

```
$ docker run -it gcr.io/broad-dsp-gcr-public/leonardo:joel-test-1 /bin/sh
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
# ls /leonardo
aou-rstudio-chart  aou-sas-chart  cromwell  cromwell-on-azure  galaxykubeman  hail-batch-terra-azure  helm-go-lib  ingress-nginx  leonardo-assembly-48ff54ef6.jar  terra-app  terra-app-setup  wds
```

**Review by LizBaldo — APPROVED** [review]
This looks good to me, but just to double check, the scope of this PR is to add the Chart, but not yet make use of it? (I don't have access to the ticket :) )

**Comment by Qi77Qi** [comment]
@LizBaldo yea exactly...just making it available..
there will be more change for injecting the proper license file as well in a follow up PR

But neither will be actually using the chart yet since https://github.com/DataBiosphere/leonardo/pull/3509 is not in yet

**Comment by jmthibault79** [comment]
jenkins retest

**Comment by jmthibault79** [comment]
Merging despite the Jenkins failure "Welder timeout" because there's no logical connection with this change.

**Pull request merged**
