### PR TITLE
[IA-2291] use ol8 docker image to resolve trivy scan issues

### PR DESCRIPTION
**Pull request by jdcanas**
Have not tested yet. Letting auto tests run here to see if the docker file change is good. 

This change is a result of this slack discussion: https://broadinstitute.slack.com/archives/G01F2P32HC1/p1605299326041200

### CODE REVIEW

**Comment by jdcanas** [comment]
jenkins retest

**Comment by rtitle** [comment]
Looks fine.. does it get rid of the trivy errors in leonardo-build?

**Comment by rtitle** [comment]
It does!

```
09:38:37 broadinstitute/leonardo:13917772e5eb (oracle 8.2)
09:38:37 =================================================
09:38:37 Total: 0 (CRITICAL: 0)
```
https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-build/8929/console

:shipit:

**Review by rtitle — APPROVED** [review]

**Comment by Qi77Qi** [comment]
can you also re-enable failing build if scan fails

**Comment by jdcanas** [comment]
Where can I do that @Qi77Qi ? not too familiar with where the scan happens in our build job, is it `/scripts/docker_build_check.sh`?

**Comment by Qi77Qi** [comment]
https://github.com/DataBiosphere/leonardo/blob/develop/docker/build.sh#L178

**Pull request merged**
