### PR TITLE
IA-3865 Add `saturnAutoCreated` label for apps created by Terra

### PR DESCRIPTION
**Pull request by Qi77Qi**
https://broadworkbench.atlassian.net/browse/IA-3865

`saturnAutoCreated` label is used in runtime to differentiate runtimes created through Terra vs ones created outside terra (such as via direct API calls or created via AoU). We should have something similar for apps as well.

Tested against dev DB and removed the labels I added manually

Should have https://github.com/DataBiosphere/terra-ui/pull/3533 merge/deployed first before this PR is merged

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by mlilynolting** [comment]
Is `LABEL` a Liquibase thing, the label of a changeset, or is it a field on an individual DB record?

**Comment by Qi77Qi** [comment]
@mlilynolting  `LABEL` is a table in leonardo DB. It has various key, value pairs for various resources.

**Review by rtitle — APPROVED** [review]
LGTM

**Comment by Qi77Qi** [comment]
Jenkins retest

**Comment by Qi77Qi** [comment]
Jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Pull request merged**
