### PR TITLE
Update wds version to 0.44.0

### PR DESCRIPTION
**Pull request by broadbot**
This PR is auto-generated by
[terra-helmfile actions/make_leo_pr](https://github.com/broadinstitute/terra-helmfile/blob/main/.github/workflows/make_leo_pr.yml), using
[github actions/github-script](https://github.com/actions/github-script).

It updates wds from chart version 0.43.0 to 0.44.0.

### CODE REVIEW

**Review by rtitle — APPROVED** [review]

**Comment by davidangb** [comment]
fiab-start failures; Jenkins retest

**Comment by davidangb** [comment]
One failure:
 

[Test Result](https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/57297/testReport/) (1 failure / +1)
[org.broadinstitute.dsde.workbench.leonardo.runtimes.RuntimeDataprocSpec.should stop/start a Dataproc cluster with workers and preemptible workers](https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/57297/testReport/junit/org.broadinstitute.dsde.workbench.leonardo.runtimes/RuntimeDataprocSpec/should_stop_start_a_Dataproc_cluster_with_workers_and_preemptible_workers/)

**Comment by rtitle** [comment]
I think that's a known flake, I can merge

**Comment by rtitle** [comment]
Nvm, thanks @LizBaldo  :)

**Pull request merged**
