### PR TITLE
[IA-4266] increase akka max-uri-length config

### PR DESCRIPTION
**Pull request by mlilynolting**
default is 2048; raise to 16K. Verified on my BEE!

### CODE REVIEW

**Review by LizBaldo — APPROVED** [review]
Thank you for fixing that!

**Review by jack-r-warren — APPROVED** [review]
LGTM! (as far as DevOps is concerned)

**Comment by mlilynolting** [comment]
jenkins retest

**Review by jdcanas — APPROVED** [review]

**Comment by mlilynolting** [comment]
jenkins retest

**Comment by mlilynolting** [comment]
jenkins retest

**Pull request merged**
