### PR TITLE
[IA-4639] Set HttpOnly flag

### PR DESCRIPTION
**Pull request by lucymcnatt**
__Jira ticket__: https://broadworkbench.atlassian.net/browse/IA-4639

### What

- Adding httpOnly flag to the leoToken cookie

### Why

> Because Leo is launching apps that allow for arbitrary compute, it is important to protect the token value from being stolen through XSS or other attacks. 

### What to test

- 

### Who tested and where

- [ ] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [ ] I validated this change 
- [ ] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

### CODE REVIEW

**Review by sarahgibs — APPROVED** [review]
Looks good. Thanks!

**Comment by lucymcnatt** [comment]
jenkins retest

**Comment by lucymcnatt** [comment]
jenkins retest

**Review by cpate4 — COMMENTED** [review]
I did a grep in our `leonardo`-codebase for `Secure;SameSite=None` and also came up with:
- cluster-site.conf
- cluster-site-gce.conf

Do either of these need the `HttpOnly` to be appended also?

**Comment by lucymcnatt** [comment]
> Do either of these need the HttpOnly to be appended also?

Since this ask was specifically for the Leo token, I think that's out of the scope (referencing the the comment above those lines)

`Append SameSite=None to cookies set by RStudio. This is required by some browsers because we render RStudio in an iframe. There does not appear to be a way within RStudio to do this, hence doing it in the proxy`

but @sarahgibs do you think we should add the httpOnly flag there as well?

**Comment by sarahgibs** [comment]
> 
> `Append SameSite=None to cookies set by RStudio. This is required by some browsers because we render RStudio in an iframe. There does not appear to be a way within RStudio to do this, hence doing it in the proxy`
> 
> but @sarahgibs do you think we should add the httpOnly flag there as well?

All cookies should be HttpOnly if possible. The concern would be if there is JavaScript in RStudio that uses the cookie. Any cookies that do not have HttpOnly set on them could be stolen with malicious JavaScript.

**Review by cpate4 — APPROVED** [review]

**Pull request merged**
