### PR TITLE
RW-10509 Refactor out buildChart functions

### PR DESCRIPTION
**Pull request by Qi77Qi**
https://precisionmedicineinitiative.atlassian.net/browse/RW-10509

Just refactoring out these buildChart argument functions so that the GKEInterpreter file is smaller (this file is getting gigantic)

### Who tested and where

- [ ] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [ ] I validated this change 
- [ ] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

### CODE REVIEW

**Review by LizBaldo — APPROVED** [review]
Thanks a lot for breaking this file up!

One little nit though, would you be able to rename `BuildHelmChartInputs.scala` to `BuildHelmChartValues.scala`?

**Comment by Qi77Qi** [comment]
@LizBaldo sure...I kinda like `BuildHelmChartInputs` more than `BuildHelmChartValues` cuz conceptually they're input values to these helm charts for helm install...but I don't feel strongly either way

**Comment by LizBaldo** [comment]
Well, this function will also be reused to regenerate the values for the helm upgrade command as well, which is why I was thinking of that name change :)

**Comment by Qi77Qi** [comment]
```
terra-quality-13512213/automation-test-a5fb4q47zpd-spec-clone errored due to List(RuntimeError(Jupyter, Welder failed to start after 10 minutes.,None,2023-07-18T21:18:40Z,Some(TraceId(1c66b23bae404705b2622c35c90af15d/3939911508519804487))))
```

this doesn't touch runtime creation. so going to merge as is

**Pull request merged**
