### PR TITLE
[IA-2574] Make referer page reliable in automation tests

### PR DESCRIPTION
**Pull request by rtitle**
This is take 2 of this change.

The original PR is [here](https://github.com/DataBiosphere/leonardo/pull/1935) but it was reverted because it was making tests unstable.

This PR is organized into 2 commits:
- https://github.com/DataBiosphere/leonardo/pull/1954/commits/27b2b7bdc74b5f5bc8ca7e42bedce6ad62994feb -- un-reverts the original change
- https://github.com/DataBiosphere/leonardo/pull/1954/commits/583d7113d17b713e12449a40767b0d8d6eaa8185 -- fixes to make it more reliable

The latter commit does the following:
- Uses `http4s` instead of `akka-http` to serve the proxy redirect page. Also uses a dedicated thread pool. I don't think this was directly related to the problem, but still nice-to-have.
- Adds logging and retries to `ProxyRedirectPage`. Again nice-to-have.
- (This is the real issue) Have each test suite start a server on separate ports. Previously, it would only run on 1 port, so when suite A finished it would stop the server causing the remaining tests in suite B to fail. Now each test suite owns their own proxy redirect server, and tests are happy.

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by rtitle** [comment]
It worked!!!

Gonna go for 10 passes.

jenkins retest

**Comment by rtitle** [comment]
2 passes

**Comment by rtitle** [comment]
3 passes

jenkins retest

**Comment by rtitle** [comment]
4 passes 

jenkins retest

**Comment by rtitle** [comment]
5 passes

jenkins retest

**Comment by rtitle** [comment]
fiab-start failed

jenkins retest

**Comment by rtitle** [comment]
6 passes 

jenkins retest

**Comment by rtitle** [comment]
7 passes

jenkins retest

**Comment by rtitle** [comment]
@xuscrbw I think this is good now if you could re-review 😁

**Review by xuscrbw — APPROVED** [review]

**Comment by rtitle** [comment]
Nooo 8th run failed :(

I don't think it's related though, error in `NotebookGCEDataSyncingSpec` which I think I've seen before.

jenkins retest

**Comment by rtitle** [comment]
8 passes

jenkins retest

**Comment by rtitle** [comment]
9 passes

**Pull request merged**
