### PR TITLE
Ia 3885 add optional timeout field 2

### PR DESCRIPTION
**Pull request by Qi77Qi**
Commit clean up of https://github.com/DataBiosphere/leonardo/pull/3064

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by LizBaldo** [comment]
jenkins retest

**Review by LizBaldo — APPROVED** [review]

**Review by mlilynolting — APPROVED** [review]

**Comment by LizBaldo** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
fiab-start failure

jenkins retest

**Comment by LizBaldo** [comment]
fiab-start failure

jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by LizBaldo** [comment]
jenkins retest

**Comment by LizBaldo** [comment]
jenkins retest

**Pull request closed without merging**
