### PR TITLE
[AJ-777] Make WDS the top level path for the standalone app

### PR DESCRIPTION
**Pull request by jordansafer**
WDS is the top level path when WDS is a standalone app, since requests through the relay listener go directly to WDS. This PR updates the config path for WDS, so when a leo client calls leo, they get the correct path.

Testing:
- Tested on a BEE, created a standalone WDS and verify that the listAppsV2 response now returns the correct proxy Url

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by aaronkanzer — APPROVED** [review]

**Review by LizBaldo — APPROVED** [review]

**Review by rtitle — APPROVED** [review]

**Comment by jordansafer** [comment]
jenkins retest

**Comment by jordansafer** [comment]
jenkins retest

**Comment by jordansafer** [comment]
jenkins retest

**Comment by jordansafer** [comment]
jenkins retest

**Pull request merged**
