### PR TITLE
Fix node security vulnerabilities

### PR DESCRIPTION
**Pull request by rtitle**
WARNING: I don't know what I'm doing!

This is to hopefully address the yellow warning on the Leo github page: https://github.com/DataBiosphere/leonardo

What I did:
1. ```npm audit fix --force```
2. committed the changes

The UI still loads on `npm start` so hopefully it is OK. (We don't actually run this UI in production, it was contributed externally.)

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by kyuksel** [comment]
I wonder if the owner of the said UI could verify that it still works with the changes. 

It may also be good to get feedback from the security team.

**Comment by rtitle** [comment]
Good point. @eap and @adrazhi in case you have any feedback.

**Comment by rtitle** [comment]
Ah no, that happened by itself by running `npm audit fix`. But that isn't flagged as a vulnerability -- maybe instead I will try running
```
npm audit fix --package-lock-only
```

**Comment by rtitle** [comment]
I ran the above and it made the same change. I think I'm just going to merge this.

**Pull request merged**
