### PR TITLE
AJ-1009: update WDS chart 0.7.0->0.13.0

### PR DESCRIPTION
**Pull request by davidangb**
__Jira ticket__: https://broadworkbench.atlassian.net/browse/AJ-1009

## Summary of changes

Point Leo at the latest WDS chart. Previous PR that did a similar thing: #3324

### Who tested and where

- [ ] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [ ] I validated this change 
- [ ] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

### CODE REVIEW

**Review by calypsomatic — APPROVED** [review]
Wow we were several charts behind!

**Review by lucymcnatt — APPROVED** [review]

**Comment by dvoet** [comment]
jenkins retest

**Review by mlilynolting — APPROVED** [review]

**Comment by lucymcnatt** [comment]
jenkins retest

**Comment by davidangb** [comment]
Jenkins retest

**Pull request merged**
