### PR TITLE
[RW-9296] Bump AoU and Hail image versions

### PR DESCRIPTION
**Pull request by dmohs**
terra-jupyter-hail:1.0.22: https://github.com/DataBiosphere/terra-docker/pull/382
terra-jupyter-aou:2.1.15: https://github.com/DataBiosphere/terra-docker/pull/383

```
% gcloud container images list-tags us.gcr.io/broad-dsp-gcr-public/terra-jupyter-hail | head -n 3
DIGEST        TAGS                            TIMESTAMP
b1d10a802ddf  1.0.22,acdf1c7,latest           2022-12-15T21:03:35
78028f0b8b78  1.0.21,8615cd1                  2022-11-15T09:44:54
```
```
% gcloud container images list-tags us.gcr.io/broad-dsp-gcr-public/terra-jupyter-aou | head -n 3
DIGEST        TAGS                   TIMESTAMP
473700884963  2.1.15                 2022-12-16T10:27:17
9fe2e3d89189  2.1.14                 2022-12-12T16:07:49
```
```
% gcloud compute images list --project=broad-dsp-gcr-public --filter='name~^custom-leo' --sort-by=~creationTimestamp --limit=3
NAME                                               PROJECT               FAMILY                 DEPRECATED  STATUS
custom-leo-image-dataproc-2-0-51-debian10-a46b242  broad-dsp-gcr-public  dataproc-custom-image              READY
custom-leo-gce-cos-image-a46b242                   broad-dsp-gcr-public  gce-custom-image                   READY
custom-leo-image-dataproc-2-0-51-debian10-215b822  broad-dsp-gcr-public  dataproc-custom-image              READY
```
---
I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by Qi77Qi** [comment]
thanks @dmohs !... since we updated hail version, https://github.com/DataBiosphere/leonardo/blob/develop/automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/notebooks/NotebookHailSpec.scala#L22 needs to be udpated as well

**Comment by dmohs** [comment]
jenkins retest

**Comment by dmohs** [comment]
jenkins retest

**Comment by dmohs** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by dmohs** [comment]
Timeout out after 120 minutes.
jenkins retest

**Comment by dmohs** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
@dmohs one thing I forgot is we need to run `gsutil cp gs://terra-docker-image-documentation/terra-docker-versions-new.json gs://terra-docker-image-documentation/terra-docker-versions-candidate.json` for this one before merging, becuase this PR updated terra-docker-hail version. `terra-docker-versions-candidate.json` contains versions of images that Terra UI should be pointing to

I just ran the cmd for this time...Going to merge this PR since I saw a green run yesterday

**Comment by dmohs** [comment]
https://fc-jenkins.dsp-techops.broadinstitute.org/job/fiab-start/88101/console
```
22:25:09 3:25AM ERR 1 execution errors:
22:25:09 workspacemanager: timed out waiting for healthy (Degraded: workspacemanager-deployment: Startup probe failed: Get "http://10.76.2.211:8080/version": dial tcp 10.76.2.211:8080: connect: connection refused)
```
jenkins retest

**Comment by dmohs** [comment]
Ha, should have refreshed. Thank you, Qi.

**Comment by Qi77Qi** [comment]
yea, that's real issue with WSM

**Pull request merged**
