### PR TITLE
[IA-2644] Remove batch nodepool create

### PR DESCRIPTION
**Pull request by jdcanas**

### CODE REVIEW

**Comment by jdcanas** [comment]
jenkins retest, fiab failure

**Review by Qi77Qi — APPROVED** [review]
👍

**Review by rtitle — APPROVED** [review]
image

Love it, :shipit:

**Review by kyuksel — COMMENTED** [review]
Thanks for taking care of this, Justin!

I noticed that Swagger also contains related pieces around [batchNodepoolCreate endpoint](https://github.com/DataBiosphere/leonardo/blob/706a7504420ea4bec686d4f761455e8502b2ddf1/http/src/main/resources/swagger/api-docs.yaml#L820) which we should probably remove as well.

Also, is there going to be a cron-jobs PR to remove related code from there as well?

**Pull request merged**
