### PR TITLE
IA-3733 fix app start bug

### PR DESCRIPTION
**Pull request by Qi77Qi**
https://broadworkbench.atlassian.net/browse/IA-3733

This PR should start up custom app properly. The bug is that previously when we check if the app is up, we're hardcoding the url to `/galaxy`, hence it will never work.

Tested in fiab and this PR should fix the bug.

This isn't sth we can meaningfully unit test. I'll add an automation test either in a separate PR or in the same PR depending on when review happens

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by yonghaoy — APPROVED** [review]

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
```
{
  "code" : 404,
  "errors" : [ {
    "domain" : "global",
    "message" : "Generic::not_found: Account deleted: 286580728785.",
    "reason" : "notFound"
  } ],
  "message" : "Generic::not_found: Account deleted: 286580728785.",
  "status" : "NOT_FOUND"
} 
```

jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
account deleted error again... jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
```
18:14:13 [WARN] Timed out rendering configs for sam.  Retrying...
```

fiab-start failure

jenkins retest

**Pull request merged**
