### PR TITLE
RW-8725 update aou to 2.1.10

### PR DESCRIPTION
**Pull request by tarekmamdouh**
\<your comments for this PR go here\>

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by tarekmamdouh** [comment]
@yonghaoy @Qi77Qi I update the aou version, I basically followed the PR commits here https://github.com/DataBiosphere/leonardo/pull/2414/files

As far as I understand I need to run this job https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-custom-image-wilson/build?delay=0sec after the PR is merged, then update reference.conf with the output from that run, please correct if I'm wrong here.

**Comment by yonghaoy** [comment]
> https://github.com/DataBiosphere/leonardo/pull/2414/files
Per https://broadworkbench.atlassian.net/wiki/spaces/IA/pages/2519564289/Integrating+new+Terra+docker+images+with+Leonardo 
There is another jenkins job called leonardo-build-custom-image. As you can see in my PR, customDataprocImage and customGceImage are updated, I think I get those values from that Jenkins job. But I couldn't find that job now...

**Review by yonghaoy — COMMENTED** [review]
Few more places that may need update: 
https://github.com/DataBiosphere/leonardo/blob/develop/automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/notebooks/NotebookHailSpec.scala#L22
https://github.com/DataBiosphere/leonardo/blob/develop/jenkins/Jenkinsfile#L23
https://github.com/DataBiosphere/leonardo/blob/develop/jenkins/gce-custom-images/create_gce_image.sh#L44

@Qi77Qi may assist how to find another Jenkins job to generate that hash value...

**Comment by Qi77Qi** [comment]
>As far as I understand I need to run this job https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-build-terra-docker/ after the PR is merged, then update reference.conf with the output from that run, please correct if I'm wrong here.

you're running it and update hash before the PR is merged

**Comment by tarekmamdouh** [comment]
@xuscrbw thank you for bumping the cached disks, I am wondering where did you get these hashes from?

Per the wiki that yonghao mentioned, I tried to run the custom image wilson jenkins job yesterday and it failed so I was going to troubleshoot it today. Does the wiki need updates?
Here's the wiki I'm referring to
https://broadworkbench.atlassian.net/wiki/spaces/IA/pages/2519564289/Integrating+new+Terra+docker+images+with+Leonardo

@yonghaoy  FYI

**Comment by Qi77Qi** [comment]
@tarekmamdouh there's no bumping disk involved..we're just updating the VM image that'll be used for launching jupyter notebooks to newly generated one (one with your new image cached)

The jenkins job might fail, but as long as it outputs the generated custom VM image, we can use them here and once tests pass, we're good

**Comment by xuscrbw** [comment]
The steps are in the doc here: 
Screen Shot 2022-09-30 at 9 25 07 AM
Also the commit was not named properly, this is not a disk update

**Comment by yonghaoy** [comment]
**I think** We also need to update aou_old to the one we are using at `2.1.8 `
https://github.com/DataBiosphere/leonardo/blob/f8e627ec136de602334c8edfc60939c7ec899afc/jenkins/gce-custom-images/prepare_gce_image.sh#L30
https://github.com/DataBiosphere/leonardo/blob/f8e627ec136de602334c8edfc60939c7ec899afc/jenkins/dataproc-custom-images/prepare-custom-leonardo-jupyter-dataproc-image.sh#L31

**Comment by tarekmamdouh** [comment]
> **I think** We also need to update aou_old to the one we are using at `2.1.8 `
> 
> https://github.com/DataBiosphere/leonardo/blob/f8e627ec136de602334c8edfc60939c7ec899afc/jenkins/gce-custom-images/prepare_gce_image.sh#L30
> 
> 
> https://github.com/DataBiosphere/leonardo/blob/f8e627ec136de602334c8edfc60939c7ec899afc/jenkins/dataproc-custom-images/prepare-custom-leonardo-jupyter-dataproc-image.sh#L31

I thought I did that already
image

**Comment by Qi77Qi** [comment]
`-old` should refer to whatever is being used in AoU prod...so only update it if AoU's prod image reference has changed

**Comment by xuscrbw** [comment]
The automation failure here is related to a known test bug

**Comment by yonghaoy** [comment]
> 

Our prod is using 2.1.7 actually. We must forget to upgrade that value last time...
https://github.com/all-of-us/workbench/search?q=terra-jupyter-aou

**Comment by Qi77Qi** [comment]
ok, in that case, think we should re-generate the VM image...

**Comment by tarekmamdouh** [comment]
hi @Qi77Qi  and @xuscrbw 
I am just following up on the status of this one, I see some changes from @xuscrbw , is there anything required from my end at the moment?

**Comment by Qi77Qi** [comment]
@tarekmamdouh  https://github.com/DataBiosphere/leonardo/pull/2878#issuecomment-1263658936
if you're not sure how to do that still, ping @xuscrbw

**Comment by Qi77Qi** [comment]
hmm looks like @xuscrbw might've went ahead and did it for u...in that case, you're all set

**Comment by tarekmamdouh** [comment]
Thank you @Qi77Qi  and @xuscrbw , please let me know what would be the next step to get this PR merged.

**Comment by xuscrbw** [comment]
Hi! I think we are just waiting for the automation tests to pass here. But that is reliant on a known issue we are working with google on

**Comment by xuscrbw** [comment]
jenkins retest

**Review by Qi77Qi — APPROVED** [review]

**Pull request merged**
