### PR TITLE
[No ticket] fix typo

### PR DESCRIPTION
**Pull request by jdcanas**

### CODE REVIEW

**Review by Qi77Qi — APPROVED** [review]
🤦‍♀️

**Review by rtitle — APPROVED** [review]
Omg.. well hopefully this didn't have much effect, welder shouldn't be swapping anyway

**Comment by jdcanas** [comment]
pesky unchecked variable names...

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by jdcanas** [comment]
jenkins retest

**Comment by rtitle** [comment]
jenkins retest again

**Comment by jdcanas** [comment]
jenkins retest 4.0 (it seems to have been a different issue each time...)

**Pull request merged**
