### PR TITLE
Update wds version to 0.42.0

### PR DESCRIPTION
**Pull request by broadbot**
This PR is auto-generated by
[terra-helmfile actions/make_leo_pr](https://github.com/broadinstitute/terra-helmfile/blob/main/.github/workflows/make_leo_pr.yml), using
[github actions/github-script](https://github.com/actions/github-script).

It updates wds from chart version 0.41.0 to 0.42.0.

### CODE REVIEW

**Comment by calypsomatic** [comment]
jenkins retest

**Comment by calypsomatic** [comment]
jenkins retest

**Comment by choover-broad** [comment]
jenkins retest

**Comment by davidangb** [comment]
Jenkins retest

**Comment by davidangb** [comment]
Jenkins retest

**Comment by davidangb** [comment]
last run, one failure:
[org.broadinstitute.dsde.workbench.leonardo.runtimes.RuntimeDataprocSpec.should stop/start a Dataproc cluster with workers and preemptible workers](https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/57107/testReport/org.broadinstitute.dsde.workbench.leonardo.runtimes/RuntimeDataprocSpec/should_stop_start_a_Dataproc_cluster_with_workers_and_preemptible_workers/)

Jenkins retest

**Comment by davidangb** [comment]
Previous failures:

https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/57107/

* [org.broadinstitute.dsde.workbench.leonardo.runtimes.RuntimeDataprocSpec.should stop/start a Dataproc cluster with workers and preemptible workers](https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/57107/testReport/org.broadinstitute.dsde.workbench.leonardo.runtimes/RuntimeDataprocSpec/should_stop_start_a_Dataproc_cluster_with_workers_and_preemptible_workers/)

https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/57100/

* [org.broadinstitute.dsde.workbench.leonardo.runtimes.RuntimeDataprocSpec.should stop/start a Dataproc cluster with workers and preemptible workers](https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/57100/testReport/org.broadinstitute.dsde.workbench.leonardo.runtimes/RuntimeDataprocSpec/should_stop_start_a_Dataproc_cluster_with_workers_and_preemptible_workers/)

https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/57096/

* [org.broadinstitute.dsde.workbench.leonardo.runtimes.RuntimeCreationDiskSpec.create runtime and attach an existing persistent disk or clone](https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/57096/testReport/junit/org.broadinstitute.dsde.workbench.leonardo.runtimes/RuntimeCreationDiskSpec/create_runtime_and_attach_an_existing_persistent_disk_or_clone/)
* [org.broadinstitute.dsde.workbench.leonardo.runtimes.RuntimeDataprocSpec.should create a Dataproc cluster with worker private access](https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/57096/testReport/junit/org.broadinstitute.dsde.workbench.leonardo.runtimes/RuntimeDataprocSpec/should_create_a_Dataproc_cluster_with_worker_private_access/)

**Pull request merged**
