### PR TITLE
IA-3781 fix swagger

### PR DESCRIPTION
**Pull request by Qi77Qi**
https://broadworkbench.atlassian.net/browse/IA-3781

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by yonghaoy — APPROVED** [review]
That is the AppStatus used in the code? I also saw Predeleting, Precreating. 
Do we need to make sure both keep in sync?

**Comment by Qi77Qi** [comment]
those `pre` statuses are more like bug...I'll fix those too

**Comment by yonghaoy** [comment]
> That is the AppStatus used in the code? I also saw Predeleting, Precreating. Do we need to make sure both keep in sync?

For example in RBS, we have https://github.com/DataBiosphere/terra-resource-buffer/blob/master/src/test/java/bio/terra/buffer/common/BackwardsCompatibilityTest.java#L35 to make sure enum in swagger can be mapped to the enum in DB

**Comment by Qi77Qi** [comment]
@yonghaoy we don't want to couple status at API level and in DB. For instance, these "pre" status aren't really helpful for users, we intend to just hide them

**Review by yonghaoy — APPROVED** [review]

**Comment by Qi77Qi** [comment]
jenkins retest

**Pull request merged**
