### PR TITLE
[WOR-1043] Bump relay version to pull in fix

### PR DESCRIPTION
**Pull request by aherbst-broad**
__Jira ticket__: https://broadworkbench.atlassian.net/browse/WOR-1043

## Summary of changes

Pulls in a fix for the azure relay listener that was breaking logging (related [PR](https://github.com/DataBiosphere/terra-azure-relay-listeners/pull/34)).

### What

- We need updated logging in the relay listener. The previous attempt was reverted due to an error introduced on relay listener bootstrap. 

### Why

- This logging [PR](https://github.com/DataBiosphere/terra-azure-relay-listeners/commits/main) in the relay listener had an errant @ cacheable notation that was causing the relay to fail on startup. 

## Testing these changes
Tested in a BEE:

Spun up WDS, imported data to a table successfully
Spun up a VM, turned on a Jupyter notebook and did a print("Hello world") successfully.
Spun up Cromwell, ran a workflow (errored out with config issues unrelated to the listener)

### What to test

- 

### Who tested and where

- [ ] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [ ] I validated this change 
- [ ] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

### CODE REVIEW

**Comment by aherbst-broad** [comment]
jenkins retest

**Comment by aherbst-broad** [comment]
jenkins retest

**Comment by aherbst-broad** [comment]
jenkins retest

**Comment by aherbst-broad** [comment]
jenkins retest

**Comment by aherbst-broad** [comment]
jenkins retest

**Comment by aherbst-broad** [comment]
jenkins retest

**Comment by aherbst-broad** [comment]
jenkins retest

**Review by LizBaldo — APPROVED** [review]
LMK if the swat tests are giving you trouble

**Comment by aherbst-broad** [comment]
jenkins retest

**Comment by aherbst-broad** [comment]
jenkins retest

**Pull request merged**
