### PR TITLE
Revert "AJ-1147: no direct policies for apps with workspace parent"

### PR DESCRIPTION
**Pull request by davidangb**
Reverts DataBiosphere/leonardo#3488

### CODE REVIEW

**Review by LizBaldo — APPROVED** [review]
Thanks!

**Review by salonishah11 — APPROVED** [review]

**Comment by LizBaldo** [comment]
jenkins retest

**Comment by LizBaldo** [comment]
jenkins retest

**Comment by LizBaldo** [comment]
[This PR](https://github.com/DataBiosphere/leonardo/pull/3496) seems to have fixed Cromwell for me on my BEE, so I am thinking we could close this one and hotfix with the fix instead of the revert?

**Comment by rtitle** [comment]
I'm sorry for being out of the loop -- just wondering if there's a quick TLDR/summary of the issue this was causing, & why it's being reverted?

**Comment by LizBaldo** [comment]
CBAS needs to impersonate the resource creator, and so removing this broke Cromwell. That being said, I do not think that we need to revert, this PR should fix it https://github.com/DataBiosphere/leonardo/pull/3496

**Pull request closed without merging**
