### PR TITLE
RW-9555 Bump AoU and Hail Image versions

### PR DESCRIPTION
**Pull request by tarekmamdouh**
\<your comments for this PR go here\>

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by tarekmamdouh** [comment]
hi @Qi77Qi  I am not sure if the jenkins tests are just flaky or there's a legit failure. Can you please help me check or point me to where can I look?

**Comment by tarekmamdouh** [comment]
jenkins retest

**Comment by tarekmamdouh** [comment]
jenkins retest

**Comment by tarekmamdouh** [comment]
jenkins retest

**Comment by tarekmamdouh** [comment]
hi @jdcanas and @xuscrbw - 
We're seeing an error in one of the jobs, but we're not sure if that's the root cause. We also can't see the new image pushed to https://pantheon.corp.google.com/gcr/images/broad-dsp-gcr-public/us/terra-jupyter-aou. 
Can someone please check what's wrong?

```
16:28:16 [io-compute-blocker-10                   ] <b><span style="color: #CD0000;">ERROR</span></b> [o.b.d.w.s.Orchestration$ :parseResponse] - {
  "causes": [],
  "message": "You cannot delete this workspace: Workspace deletion blocked by child resources",
  "source": "FireCloud",
  "stackTrace": [],
  "timestamp": 1676910496686
}
16:28:16 [io-compute-blocker-10                   ] <span style="color: #CD0000;">WARN </span> [b.d.w.l.LeonardoTestSuite:$anonfun$warn$2] - Failed to delete billing project: leonardo-test-95fe450a97414ab1
org.broadinstitute.dsde.workbench.service.RestException: {
  "causes": [],
  "message": "You cannot delete this workspace: Workspace deletion blocked by child resources",
  "source": "FireCloud",
  "stackTrace": [],
  "timestamp": 1676910496686
}
	at org.broadinstitute.dsde.workbench.service.RestClient.throwRestException(RestClient.scala:123)
	at org.broadinstitute.dsde.workbench.service.RestClient.parseResponse(RestClient.scala:119)
	at org.broadinstitute.dsde.workbench.service.RestClient.parseResponse$(RestClient.scala:113)
	at org.broadinstitute.dsde.workbench.service.Orchestration$.parseResponse(Orchestration.scala:881)
	at org.broadinstitute.dsde.workbench.service.RestClient.requestWithJsonContent(RestClient.scala:149)
	at org.broadinstitute.dsde.workbench.service.RestClient.deleteRequest(RestClient.scala:182)
	at org.broadinstitute.dsde.workbench.service.RestClient.deleteRequest$(RestClient.scala:181)
	at org.broadinstitute.dsde.workbench.service.Orchestration$.deleteRequest(Orchestration.scala:881)
	at org.broadinstitute.dsde.workbench.service.Orchestration$workspaces$.delete(Orchestration.scala:286)
	at org.broadinstitute.dsde.workbench.leonardo.BillingProjectUtils.$anonfun$deleteWorkspaceAndBillingProject$3(LeonardoSuite.scala:113)
	at apply @ org.broadinstitute.dsde.workbench.leonardo.BillingProjectUtils.$anonfun$deleteWorkspaceAndBillingProject$2(LeonardoSuite.scala:112)
	at flatMap @ org.broadinstitute.dsde.workbench.leonardo.BillingProjectUtils.$anonfun$deleteWorkspaceAndBillingProject$2(LeonardoSuite.scala:112)
	at apply @ org.broadinstitute.dsde.workbench.leonardo.TestUser.authToken(LeonardoTestUtils.scala:777)
	at flatMap @ org.broadinstitute.dsde.workbench.leonardo.BillingProjectUtils.$anonfun$deleteWorkspaceAndBillingProject$1(LeonardoSuite.scala:111)
	at apply @ org.broadinstitute.dsde.workbench.leonardo.TestUser.authToken(LeonardoTestUtils.scala:777)
	at flatMap @ org.broadinstitute.dsde.workbench.leonardo.BillingProjectUtils.deleteWorkspaceAndBillingProject(LeonardoSuite.scala:110)
	at delay @ org.broadinstitute.dsde.workbench.util2.ExecutionContexts$.$anonfun$cachedThreadPool$2(ExecutionContexts.scala:30)
16:28:16 [io-compute-blocker-10                   ] <span style="color: #1E90FF;">INFO </span> [b.d.w.l.LeonardoTestSuite:$anonfun$info$5] - Stopped proxy redirect server
[info] Run completed in 1 hour, 31 minutes, 59 seconds.
[info] Total number of tests run: 60
[info] Suites: completed 18, aborted 0
[info] Tests: succeeded 59, failed 1, canceled 1, ignored 3, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error] 	org.broadinstitute.dsde.workbench.leonardo.LeonardoTerraDockerSuite
[error] (Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
```

**Comment by jdcanas** [comment]
Seems the test failure is unlikely to have anything to do with this PR, the automation tests can be rather flaky. Nothing better to do than re-run :(

**Comment by tarekmamdouh** [comment]
jenkins retest

**Comment by tarekmamdouh** [comment]
> 

thanks @jdcanas , how about the image not published in the registry, can someone manually publish it please?

**Comment by jdcanas** [comment]
Hmmm...  it seems there's an issue in the terra-docker Dockerfile for hail, which is causing the image  build job to error out. 

Details and fix here: https://github.com/DataBiosphere/terra-docker/pull/395/files

**Comment by jdcanas** [comment]
So the hail image is now fixed (in so far that it is building), but the aou docker build failed on step 19. Seems like a bug in the dockerfile, have you been able to build locally?

```
Step 19/47 : RUN mkdir -p /tmp/bolt-lmm &&   cd /tmp/bolt-lmm &&   curl -L -o bolt-lmm.tar.gz "[https://storage.googleapis.com/broad-alkesgroup-public/BOLT-LMM/downloads/BOLT-LMM_${BOLT_LMM_VERSION}.tar.gz](https://storage.googleapis.com/broad-alkesgroup-public/BOLT-LMM/downloads/BOLT-LMM_$%7BBOLT_LMM_VERSION%7D.tar.gz)" &&   tar -xvzf bolt-lmm.tar.gz &&   mv "BOLT-LMM_${BOLT_LMM_VERSION}" /opt/bolt-lmm &&   ln -s "/opt/bolt-lmm/bolt" /bin/bolt &&   cd $HOME &&   rm -rf /tmp/bolt-lmm
 ---> Running in 7adba75ea142
[91m  % Total    % Received % Xferd  Average Speed   Time    Time [0m[91m    Time  Current
                        [0m[91m      [0m[91m   Dload  U[0m[91mpload   To[0m[91mtal   Spen[0m[91mt    Left [0m[91m Speed

  0 [0m[91m    0    [0m[91m0     0    0[0m[91m     0   [0m[91m   0 [0m[91m     0 --:--:-- --:--:[0m[91m--[0m[91m --:-[0m[91m-:--     0[0m[91m
100   225  100   225    0     0    868      0 --:--:-- --:[0m[91m--:-- --:--:--   87[0m[91m5
[0m[91m
gzip: stdin: not in gzip format
[0m[91mtar: Child returned status 1
tar: Error is not recoverable: exiting now
[0mThe command '/bin/sh -c mkdir -p /tmp/bolt-lmm &&   cd /tmp/bolt-lmm &&   curl -L -o bolt-lmm.tar.gz "[https://storage.googleapis.com/broad-alkesgroup-public/BOLT-LMM/downloads/BOLT-LMM_${BOLT_LMM_VERSION}.tar.gz](https://storage.googleapis.com/broad-alkesgroup-public/BOLT-LMM/downloads/BOLT-LMM_$%7BBOLT_LMM_VERSION%7D.tar.gz)" &&   tar -xvzf bolt-lmm.tar.gz &&   mv "BOLT-LMM_${BOLT_LMM_VERSION}" /opt/bolt-lmm &&   ln -s "/opt/bolt-lmm/bolt" /bin/bolt &&   cd $HOME &&   rm -rf /tmp/bolt-lmm' returned a non-zero code: 2
````

**Comment by tarekmamdouh** [comment]
@jdcanas It fails locally for me as well, I assumed it was tested as per https://github.com/DataBiosphere/terra-docker/pull/393.

```esgroup-public/BOLT-LMM/downloads/BOLT-LMM_${BOLT_LMM_VERSION}.tar.gz" &&   tar -xvzf bolt-lmm.tar.gz &&   mv "BOLT-LMM_${BOLT_LMM_VERSION}" /opt/bolt-lmm &&   ln -s "/opt/bolt-lmm/bolt" /bin/bolt &&   cd $HOME &&   rm -rf /tmp/bolt-lmm
 ---> Running in eda44482c612
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   225  100   225    0     0   4166      0 --:--:-- --:--:-- --:--:--  4166

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c mkdir -p /tmp/bolt-lmm &&   cd /tmp/bolt-lmm &&   curl -L -o bolt-lmm.tar.gz "https://storage.googleapis.com/broad-alkesgroup-public/BOLT-LMM/downloads/BOLT-LMM_${BOLT_LMM_VERSION}.tar.gz" &&   tar -xvzf bolt-lmm.tar.gz &&   mv "BOLT-LMM_${BOLT_LMM_VERSION}" /opt/bolt-lmm &&   ln -s "/opt/bolt-lmm/bolt" /bin/bolt &&   cd $HOME &&   rm -rf /tmp/bolt-lmm' returned a non-zero code: 2
```

 I'll ping danking to see if it builds for him.

**Comment by tarekmamdouh** [comment]
it does seem to build here
https://github.com/DataBiosphere/terra-docker/actions/runs/4188218090/jobs/7259070580

I'm wondering what would be the difference

**Comment by tarekmamdouh** [comment]
This URL is not valid
https://storage.googleapis.com/broad-alkesgroup-public/BOLT-LMM/downloads/BOLT-LMM_${BOLT_LMM_VERSION}.tar.gz

Somehow the env variable doesn't get replaced in the URL

**Comment by yonghaoy** [comment]
@n8landolt might have a similar issue before on https://github.com/DataBiosphere/terra-docker/pull/345

**Comment by jdcanas** [comment]
Hmm... I'm not familiar with `BOLT_LMM`, but when I try the curl locally it does not work. It pulls data down (as indicated by the log above), but for both the old version and new version (`v2.3.6` and `v2.4`) the contents received are a 404 essentially
```<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: broad-alkesgroup-public/BOLT-LMM/downloads/BOLT-LMM_v2.3.6.tar.gz</Details></Error>% ```

Is anyone able to investigate the source to ensure the command for downloading `BOLT-LMM` is still valid?I get unauthorized complaints in my browser when I try to access the curl URL directly, so it seems the source of that package is the culprit.

Seems the fix will require an update to the terra-jupyter-aou resolving the `BOLT-LMM` install

**Comment by tarekmamdouh** [comment]
@n8landolt Do you have some time to help us with this issue please?

**Comment by n8landolt** [comment]
@tarekmamdouh 
Let me check with the team.
From the little investigation I did, it seems like some of the Alkes Group infrastructure is improperly configured. I think someone will need to get in touch with them directly.

**Comment by jdcanas** [comment]
Yeah, it seems to be an issue with a package  AOU dockerfile is dependent on. You can always comment out the installation of that specific package if you want to get a version out ASAP, and debug + get another version out once they (the broad group that supports that package) help to solve the issue

**Comment by tarekmamdouh** [comment]
Some more info about this one, quoting from a slack channel:
"gs://broad-alkesgroup-public. We turned off public access last week due to a large download fees that were being incurred.  The team is currently looking at how to separate the data into more logical useful units." 
I am trying to figure out if there's another way to download the package.

**Comment by tarekmamdouh** [comment]
@jdcanas seems like the image was published finally
https://pantheon.corp.google.com/gcr/images/broad-dsp-gcr-public/us/terra-jupyter-aou@sha256:478bdf5f738c841ddf8d99fa232f6e188d5b2d8f21bf6c806cb1076995d4d45a/details

 Can you please help me what to update now?

**Comment by tarekmamdouh** [comment]
Custom image generation is in progress
https://github.com/DataBiosphere/leonardo/actions/runs/4306882359

**Review by LizBaldo — APPROVED** [review]
Glad the image was made available again 👍

**Comment by tarekmamdouh** [comment]
jenkins retest

**Pull request merged**
