### PR TITLE
WX-1387 Remove unused helm values

### PR DESCRIPTION
**Pull request by jgainerdewar**
__Jira ticket__: https://broadworkbench.atlassian.net/browse/WX-1387

## Dependencies
Associated with https://github.com/broadinstitute/terra-helmfile/pull/4830

### What

- Remove values that are unused in the chart. 

### Why

- Dead code is bad and we don't want it!

### What to test

- 

### Who tested and where

I tested in a BEE both with and without the associated updates to the charts.

- [x] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [x] I validated this change 
- [ ] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

### CODE REVIEW

**Comment by jgainerdewar** [comment]
jenkins retest

**Review by THWiseman — APPROVED** [review]

**Review by salonishah11 — APPROVED** [review]

**Comment by jgainerdewar** [comment]
jenkins retest

**Comment by jgainerdewar** [comment]
Jenkins retest

**Review by Qi77Qi — APPROVED** [review]

**Comment by Qi77Qi** [comment]
the change only affects workflows...should be safe to merge as long as they look good from workflow team's perspective

**Pull request merged**
