### PR TITLE
[PROD-848] Bump ProxyDAO timeouts to 10s

### PR DESCRIPTION
**Pull request by mlilynolting**
__Jira ticket__: https://broadworkbench.atlassian.net/browse/PROD-848

## Summary of changes

These methods might be responsible for the "due to 5 seconds" error message. And they are certainly directly responsible for a lot of less-visible 5-second timeouts in the logs.

See https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22broad-dsde-prod%22%0Aresource.labels.cluster_name%3D%22terra-prod%22%0Aresource.labels.location%3D%22us-central1%22%0A%2528%22%205%20seconds%22%20OR%20jsonPayload.traceId%3D%22bdfec218d1708513604d542b9482ca69%2F16740177414313443382%22%2529;cursorTimestamp=2023-07-13T18:04:21.555799867Z;aroundTime=2023-07-13T18:04:49.206413505Z;duration=PT15M?project=broad-dsde-prod&authuser=0&pli=1&rapt=AEjHL4NsumJuK1LY-fPW17pJNXmsIIbYC-zYyokmBWNwLyh6jB-so52R4aN6Zcwn7mFMxb6lnJIl45ZSQ-pN-ER7TBKV94iqTg

Runtimes fail to start, showing "failed due to 5 seconds". I'm fairly sure that the async call to getBlob (while validating user script startup) is the source of our 5 seconds timeout error, but I can't find the smoking gun (where it would actually hit the proxy to attempt to access the runtime). Above are some logs that illustrate what I mean - the runtime is starting up successfully, and we see Google call successes for updateInstanceMetadata, startAsync, and getInstance. But the next call, to getBlob, doesn't get logged. Instead we get a generic "error executing async task" -- and getBlob is called async, unlike the others.

You can also see that there are a ton of 5 second timeoutExceptions because getRuntimeTargetHost is bombing so hard. Even though I can't confirm the exact code flow that's killing runtime start, I'm confident enough that the Proxy.get*TargetHost timeouts need to get bumped that I'm resurrecting this PR.

## Testing these changes

See https://github.com/DataBiosphere/leonardo/commit/0c3def79b3ad845573a1d910b0bfc672d6426065 for my attempt to simulate.

See https://github.com/DataBiosphere/leonardo/pull/3499/files for the new PR with unique timeout durations for diagnosis.

### Who tested and where

- [ ] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [ ] I validated this change 
- [ ] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

### CODE REVIEW

**Review by jdcanas — APPROVED** [review]

**Review by LizBaldo — APPROVED** [review]
Good find!

**Comment by mlilynolting** [comment]
jenkins multitest

**Comment by mlilynolting** [comment]
jenkins retest

**Comment by mlilynolting** [comment]
Last two swat runs had one failure each, but not in the same test. Which means that each one has a passing version of the other's failure. Merging as if swat tests succeeded.

**Pull request merged**
