### PR TITLE
fix(IA-4721): upgrade logback to latest version

### PR DESCRIPTION
**Pull request by cpate4**
__Jira ticket__: https://broadworkbench.atlassian.net/browse/IA-4721

### What

- upgrading logback to latest version

### Why

- to take advantage of latest fixes in the library (documented [here](https://logback.qos.ch/news.html#1.3.14))

### What to test

- 

### Who tested and where

- [ ] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [ ] I validated this change 
- [ ] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

### CODE REVIEW

**Comment by cpate4** [comment]
... interesting because the build failure (`HttpDockerDAOSpec`:`'detect invalid dockerhub image if image doesn't have proper environment variables set'`) has the exact same strings (and is also failing on my local system on the `develop` branch - 🤔 )

**Review by cindy-broadinstitute — APPROVED** [review]

**Comment by cpate4** [comment]
jenkins retest

**Comment by cpate4** [comment]
jenkins retest

**Comment by zbedo** [comment]
👍🏻

**Pull request merged**
