### PR TITLE
AJ-955 - Pass in Leonardo Url to Wds to support cloning

### PR DESCRIPTION
**Pull request by yuliadub**
__Jira ticket__: https://broadworkbench.atlassian.net/browse/AJ-955

WDS

## Summary of changes

WDS during start up in cloning mode in its destination instance will ask leonardo for the WDS endpoint url of the source workspace of the clone. This change propagates the Leo url into WDS to enable that call.

### What

- adding Leo url to WDS app

### Why

- need Leo url to support cloning

### What to test

- this is simply a configuration addition (cromwell receives the leo url today already) but I did verify this in my BEE! 

### Who tested and where

- [ ] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [ ] I validated this change 
- [ ] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

### CODE REVIEW

**Comment by calypsomatic** [comment]
Gotta update the [unit tests](https://github.com/DataBiosphere/leonardo/blob/9d5d754856cb37e4c9a13e1e39c154bc1bfdcd79/http/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/util/AKSInterpreterSpec.scala#L189) for that method!

**Comment by yuliadub** [comment]
jenkins retest

**Comment by yuliadub** [comment]
jenkins retest

**Comment by yuliadub** [comment]
jenkins retest

**Comment by yuliadub** [comment]
jenkins retest

**Review by davidangb — APPROVED** [review]

**Review by calypsomatic — APPROVED** [review]

**Comment by yuliadub** [comment]
jenkins retest

**Comment by yuliadub** [comment]
jenkins retest

**Comment by yuliadub** [comment]
jenkins retest

**Comment by yuliadub** [comment]
jenkins retest

**Comment by yuliadub** [comment]
jenkins retest

**Comment by yuliadub** [comment]
jenkins retest

**Comment by yuliadub** [comment]
jenkins retest

**Comment by yuliadub** [comment]
jenkins retest

**Pull request merged**
