### PR TITLE
Set workspace name/bucket in environment variable

### PR DESCRIPTION
**Pull request by rtitle**
My attempt at:
https://github.com/databiosphere/leonardo/issues/704
https://github.com/DataBiosphere/terra-ui/issues/986

Acceptance criteria: the user is able to access the following environment variables from a notebook (python or R):
- `WORKSPACE_NAMESPACE` -- the google project, e.g. `fc-product-demo`
- `WORKSPACE_NAME` -- the workspace name, e.g. `try-saturn`
- `WORKSPACE_BUCKET` -- the workspace bucket, e.g. `gs://fc-4205396d-2cde-4436-8903-9b374dac5bbf`

The general approach here is to parse the CWD of the notebook to get the workspace name. By convention Terra and AoU localizes notebooks to directories named by the workspace. This approach won't work if we start launching notebooks from other directories. 

The above is done at kernel startup time. It needs to be kernel startup, not cluster startup, because kernels start in the context of a workspace, while clusters start in the context of a project. I achieved this by creating a `kernel_bootstrap.sh` script which sets the appropriate EVs then starts the kernel. I also investigated doing this with a [python startup script](https://stackoverflow.com/questions/45818538/where-can-i-put-a-startup-script-in-jupyter). This worked, but (a) it was python only, so a different solution was needed for R; and (b) we don't need to modify the kernel state, just set EVs, so a bash script that can be commonly used for Python and R is appropriate for this.

A future enhancement might be to not use the notebook CWD, and instead pass information from Terra UI to the cluster somehow. This might be less brittle, but the general approach of using `kernel_bootstrap.sh` should still work. So I think this is a good first pass, and will add value to users today.

Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by rtitle** [comment]
jenkins retest

**Comment by rtitle** [comment]
jenkins retest

**Comment by mbookman** [comment]
Would also resolve https://github.com/DataBiosphere/terra-ui/issues/1039.

**Comment by rtitle** [comment]
jenkins retest

**Comment by rtitle** [comment]
jenkins retest

**Comment by rtitle** [comment]
jenkins retest

**Comment by rtitle** [comment]
docker build is having issues with keyserver :( jenkins retest

**Comment by rtitle** [comment]
one more jenkins retest

**Pull request merged**
