### PR TITLE
[IA-4938] upgrade workbench-libs to get the new bouncycastle 1.78

### PR DESCRIPTION
**Pull request by mlilynolting**
__Jira ticket__: https://broadworkbench.atlassian.net/browse/IA-4938

## Summary of changes

Vulnerability in bouncycastle-1.76, a Leonardo transitive dependency. Upgrade to a version of workbench-libs which uses v1.78.

### What to test

- App compiles and runs; dependency tree has bouncycastle-1.78

### Who tested and where

- [x] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [x] I validated this change 
- [ ] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

### CODE REVIEW

**Comment by mlilynolting** [comment]
We've failed swat tests twice, but not the same place both times. Here's the latest 504s: 
https://github.com/broadinstitute/terra-github-workflows/actions/runs/9132193924/job/25113028819
https://github.com/broadinstitute/terra-github-workflows/actions/runs/9132217836/job/25113108783

**Comment by LizBaldo** [comment]
Let's rerun and see, integration tests should be a lot more stable now

**Comment by mlilynolting** [comment]
Changing the workbench libs hash could have brought in some other dependency changes with unintended effects.

**Comment by mlilynolting** [comment]
Azure automation tests failed again: https://github.com/broadinstitute/terra-github-workflows/actions/runs/9132610533
But other swat tests passed: https://github.com/DataBiosphere/leonardo/actions/runs/9132350249/job/25114216692?pr=4569

**Comment by mlilynolting** [comment]
Azure automation tests keep failing; summarized in thread https://broadinstitute.slack.com/archives/CA3NP1733/p1715978100759569

Still not sure if it's due to this PR; seems like it's failing to set up the billing project correctly and might be using nonsensical tenant and subscription IDs.

**Review by aherbst-broad — APPROVED** [review]

**Review by cpate4 — APPROVED** [review]
quick ... MERGE! (... 
before the stars and moons shift and there is a hole in the space-time continuum - 🤓)

**Pull request merged**
