### PR TITLE
[no ticket] Fix retry for KernelNotReadyException

### PR DESCRIPTION
**Pull request by rtitle**
I was looking more at the Dataproc kernel issue. I feel like there are 2 problems:

1. The kernel dies on Dataproc for some reason (still not sure why)
2. The automation tests intend to retry `KernelNotReadyException`, but this wasn't working

This PR hopefully fixes (2).

Note I haven't really fully tested this, may `multi-test` this PR.

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by Qi77Qi — APPROVED** [review]
that's awesome! thank you so much!

**Comment by rtitle** [comment]
multi-test

**Comment by rtitle** [comment]
multi-test

**Comment by kyuksel** [comment]
multi-test

**Review by kyuksel — APPROVED** [review]
🎉  🤞🏼 
Thank you very much, Rob!
Launched another `multi-test`ing figuring the day is quite young 😊

**Pull request merged**
