### PR TITLE
IA-3687 Add timeout for disk creation failure and update disk status properly

### PR DESCRIPTION
**Pull request by Qi77Qi**
\<your comments for this PR go here\>

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by n8landolt — APPROVED** [review]
Looks good to me. Seems like there's a little bit of missing preexisting test coverage.
I'd suggest waiting for at least one other person to approve before merging!

**Comment by Qi77Qi** [comment]
thanks @n8landolt for review...the test coverage thing is just saying for the diff, we're hitting lower than target coverage...But we're pretty loose abt that typically...We do have unit test covering the timeout case, so I think we're good

**Review by xuscrbw — APPROVED** [review]
lgtm

**Comment by xuscrbw** [comment]
This is an error on the Automation test error here. I don't think this is related to this PR?

"errors":[{"errorMessage":"com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found\nPOST [https://container.googleapis.com/v1/projects/terra-quality-4c1ed45e/locations/us-central1-a/clusters\n{\n](https://container.googleapis.com/v1/projects/terra-quality-4c1ed45e/locations/us-central1-a/clusters/n%7B/n)  \"code\" : 404,\n  \"errors\" : [ {\n    \"domain\" : \"global\",\n    \"message\" : \"Generic::not_found: Account deleted: 10912662834.\",\n    \"reason\" : \"notFound\"\n  } ],\n  \"message\" : \"Generic::not_found: Account deleted: 10912662834.\",\n  \"status\" : \"NOT_FOUND\"\n} (of class com.google.api.client.googleapis.json.GoogleJsonResponseException)","timestamp":"2022-09-19T14:12:06.205Z","action":"createGalaxyApp","source":"cluster","googleErrorCode":null,"traceId":null}],"status":"ERROR","proxyUrls":{},"diskName":null,"customEnvironmentVariables":{},"auditInfo":{"creator":"ron.weasley@quality.firecloud.org","createdDate":"2022-09-19T14:11:59.912527Z","destroyedDate":null,"dateAccessed":"2022-09-19T14:11:59.912527Z"},"appType":"CUSTOM"}"

**Comment by Qi77Qi** [comment]
oh interesting... thanks @xuscrbw for looking at the failure..yea that shouldn't be related...

jenkins retest

**Pull request merged**
