### PR TITLE
Revert "[IA-2346] [jenkins-generated-pr] Automated custom image hash update"

### PR DESCRIPTION
**Pull request by jdcanas**
Testing the most recent merge to see if it broke tests - a lot of failure are with notebooks

### CODE REVIEW

**Comment by rtitle** [comment]
I think the failures only started recently and this was merged last week (Thu), so this probably isn't the issue (I hope)..

**Comment by Qi77Qi** [comment]
Sun is first time I noticed these failures.

**Comment by rtitle** [comment]
`dev-deploy` test runs seem to be passing 🤔 

https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/

**Comment by jdcanas** [comment]
Yeah, I'm skeptical too, but it cant hurt to see if these pass consistently

**Pull request closed without merging**
