### PR TITLE
[QA-1666] Extending timeout for HailSpec

### PR DESCRIPTION
**Pull request by xuscrbw**
Noticing the HailSpec failing consistently, but it doesn't actually seem like it's an issue with the product. Having been seeing a kernel timeout, so will first extend this timeout to see if it reduces the frequency.

I purposefully exaggerated the timeout to 10 minutes. It should never get to this and it is also only done on 1 test.
---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by xuscrbw** [comment]
multi-test

**Review by Qi77Qi — APPROVED** [review]
let's give it a try :shipit:

**Comment by xuscrbw** [comment]
jenkins retest

**Comment by xuscrbw** [comment]
AppLifecycleSpec.create and delete a CROMWELL app error

**Comment by xuscrbw** [comment]
jenkins retest

**Comment by xuscrbw** [comment]
multi-test

**Pull request merged**
