### PR TITLE
updates cromwell-helm from version 0.2.77 to 0.2.84

### PR DESCRIPTION
**Pull request by mspector**
This is normally performed by a GitHub action, but I couldn't make it work and got impatient.

### CODE REVIEW

**Comment by cjllanwarne** [comment]
jenkins retest

**Review by cjllanwarne — APPROVED** [review]

**Comment by mspector** [comment]
jenkins retest

**Comment by mspector** [comment]
jenkins retest

**Review by jgainerdewar — APPROVED** [review]
Approving now so the lack of a second thumb doesn't stand in the way of merging this when tests finally pass.

**Comment by mspector** [comment]
jenkins retest

**Comment by mspector** [comment]
jenkins retest

**Comment by mspector** [comment]
jenkins retest

**Pull request merged**
