### PR TITLE
[no ticket] Take advantage of google sdk's new APIs

### PR DESCRIPTION
**Pull request by Qi77Qi**
Related PR https://github.com/broadinstitute/workbench-libs/pull/941

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
multi-test

**Comment by Qi77Qi** [comment]
leonardo build failed

jenkins retest

**Comment by Qi77Qi** [comment]
multi-test

**Review by xuscrbw — APPROVED** [review]
LGTM

Is this change something that we would notice improvements from? Not having to handle async seems like it would definitely make reliability better, but wasn't sure how much better it would be compared to ComputePollOperation

**Comment by Qi77Qi** [comment]
@xuscrbw not sure about improvements around performance...but I think it'll definitley make it easier for us to debug error  since now we have the original Operation that we can see the error...

**Pull request merged**
