### PR TITLE
[IA-4400] Point to TARL hash with HttpOnly back in the cookie response

### PR DESCRIPTION
**Pull request by LizBaldo**
__Jira ticket__: https://broadworkbench.atlassian.net/browse/IA-4400

### CODE REVIEW

**Comment by LizBaldo** [comment]
@lucymcnatt I was able to successfully submit an Azure workflow on my BEE (the one from the manual E2E test) so this should be good to go 👍

**Review by mlilynolting — APPROVED** [review]

**Review by rtitle — APPROVED** [review]

**Review by lucymcnatt — APPROVED** [review]

**Comment by LizBaldo** [comment]
fiab-start failed
jenkins retest

**Comment by LizBaldo** [comment]
jenkins retest

**Comment by LizBaldo** [comment]
Last jenkins failure due to permission propagation - unrelated to this change so merging now

**Pull request merged**
