### PR TITLE
Bump GKM to 2.5.2

### PR DESCRIPTION
**Pull request by afgane**
This adds Expression Tools section in Galaxy.

### CODE REVIEW

**Review by LizBaldo — APPROVED** [review]
LGTM! Let me know when you want to try out using these new apache proxy configs as well :)

**Comment by LizBaldo** [comment]
jenkins retest

**Comment by LizBaldo** [comment]
jenkins retest

**Comment by LizBaldo** [comment]
@afgane are you good if I merge this?

**Comment by afgane** [comment]
Yes please. (We'll do the testing of the new headers separately.)

**Pull request merged**
