### PR TITLE
[RW-11775][risk=no] upgrade sas and rstudio to increase proxy size limit

### PR DESCRIPTION
**Pull request by yonghaoy**
Chart is published here: https://github.com/broadinstitute/terra-helmfile/commit/798eecec36dc0230f7c307a83e3872c7427cf786
This will increase the default max size to nginx proxy and unblock upload feature in both apps

__Jira ticket__: https://broadworkbench.atlassian.net/browse/[ticket_number]

### What

-

### Why

-

### What to test

- 

### Who tested and where

- [ ] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [ ] I validated this change 
- [ ] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

### CODE REVIEW

**Review by Qi77Qi — APPROVED** [review]

**Comment by Qi77Qi** [comment]
@LizBaldo do we still need the version specified in both the docker file and reference.conf?

**Comment by LizBaldo** [comment]
Yes, for GKE apps, we still need to update both files

**Review by mlilynolting — APPROVED** [review]

**Comment by yonghaoy** [comment]
jenkins retest

**Comment by yonghaoy** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
verified RStudio app works in BEE...SAS isn't easy to verify in a BEE since it requires an AoU project, so I'll check after the PR merge

**Pull request merged**
