### PR TITLE
IA-3868: update bioconductor reference images

### PR DESCRIPTION
**Pull request by lucymcnatt**
- [ ] make sure terra-docker-versions-candidate.json is accurate

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by Qi77Qi — APPROVED** [review]
looks great!.. :shipit: 🎉

**Comment by Qi77Qi** [comment]
oh before merging, make sure u did [this](https://github.com/DataBiosphere/terra-docker/blob/master/CONTRIBUTING.md#terra-ui-representation)... basically run `gsutil cp gs://terra-docker-image-documentation/terra-docker-versions-new.json gs://terra-docker-image-documentation/terra-docker-versions-candidate.json`

**Comment by lucymcnatt** [comment]
Been trying this but keep getting a 401 error :( `Anonymous caller does not have storage.objects.create access to the Google Cloud Storage object`, do I need a firecloud account?

**Comment by Qi77Qi** [comment]
> Been trying this but keep getting a 401 error :( Anonymous caller does not have storage.objects.create access to the Google Cloud Storage object, do I need a firecloud account?

you should be able to do this with Broad account...sth like `gcloud auth login --activate <your broad email>`

I just did it for now...but u can still try running the cmd to make sure u have proper permission

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
```
terra-quality-a55c8078/automation-test-awrv5tq4z errored due to List(RuntimeError(Failed to transition Gcp/terra-quality-a55c8078/automation-test-awrv5tq4z from status Creating within the time limit: 30 minutes,None,2022-12-10T02:29:41Z,Some(TraceId(400dd660cd6e4c4993a774b0afe8a6a6/3939911508519804487))))
```

jenkins retest

**Pull request merged**
