### PR TITLE
IA-3052 Fix no disk space left error for rstudiospec

### PR DESCRIPTION
**Pull request by Qi77Qi**
\<your comments for this PR go here\>

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by Qi77Qi** [comment]
multi-test

**Comment by kyuksel** [comment]
Should the [reference](https://github.com/DataBiosphere/leonardo/blob/4e9ff04295250185ab2adae0cee16b7c25608449/automation/src/test/resources/reference.conf#L6) in `automation` be removed too?

**Comment by kyuksel** [comment]
There's [another reference](https://github.com/DataBiosphere/leonardo/blob/4e9ff04295250185ab2adae0cee16b7c25608449/jenkins/Jenkinsfile#L160) in Jenkinsfile.

**Comment by Qi77Qi** [comment]
@kyuksel I dont think so...the base image is used as default image for most tests, which makes sense if the test doesn't need to validate image specific features

**Review by kyuksel — APPROVED** [review]
👍🏼 pending removing reference to the removed image in Jenkinsfile

**Comment by kyuksel** [comment]
> I dont think so...the base image is used as default image for most tests, which makes sense if the test doesn't need to validate image specific features

Ah yea that makes sense.

**Comment by Qi77Qi** [comment]
multi-test

**Comment by Qi77Qi** [comment]
leonado-build is not happy

jenkins retest

**Comment by Qi77Qi** [comment]
multi-test

**Comment by Qi77Qi** [comment]
one multi-test failed with 

```
message: Failed to create runtime terra-quality-08813be7/automation-test-abaghp1wz, status: 500 Internal Server Error body: {"source":"leonardo","message":"HTTP connection closed: https://sam-fiab.dsde-qa.broadinstitute.org:443","statusCode":500,"exceptionClass":"class java.net.SocketException","traceId":null}
```

Going to merge this

**Pull request merged**
