### PR TITLE
Add platform to mysql docker run commands

### PR DESCRIPTION
**Pull request by mikenev**
Add the --platform params to the docker run command, otherwise M1 macs error out starting up the image.

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [x] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by Qi77Qi** [comment]
cc @andy7i about this PR

**Review by andy7i — APPROVED** [review]
didn't test it but seems reasonable

**Comment by andy7i** [comment]
this seems like a better approach than mine: https://github.com/DataBiosphere/leonardo/pull/3023

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
leonardo-build failed...jenkins retest

**Comment by Qi77Qi** [comment]
```
10:25:45 "--platform" is only supported on a Docker daemon with experimental features enabled
10:25:45 running mysql validation...
10:25:45 "--platform" is only supported on a Docker daemon with experimental features enabled
10:25:45 mysql validation failed.
```

This might not be possible until we move away from running tests in jenkins

**Comment by mikenev** [comment]
Abandoning since it causes problems with jenkins tests.

**Comment by Qi77Qi** [comment]
hey @mikenev thanks for working on this...I'm going to leave this PR open for now and hopefully we'll be able to fix the CI soon

**Pull request closed without merging**
