### PR TITLE
WX-862: Update Cromwell version to 0.2.175

### PR DESCRIPTION
**Pull request by broadbot**
This PR is auto-generated by
[Cromwhelm actions/make_leo_pr](https://github.com/broadinstitute/cromwhelm/blob/main/.github/workflows/make_leo_pr.yml), using
[github actions/github-script](https://github.com/actions/github-script).

It updates cromwell-helm from version 0.2.174 to 0.2.175.

### CODE REVIEW

**Comment by cjllanwarne** [comment]
jenkins retest

**Comment by cjllanwarne** [comment]
jenkins retest

**Comment by jgainerdewar** [comment]
jenkins retest

**Review by rtitle — APPROVED** [review]

**Comment by rtitle** [comment]
Closing in favor of https://github.com/DataBiosphere/leonardo/pull/3084

**Pull request closed without merging**
