### PR TITLE
[IA-4147] generate and publish leonardo java client library

### PR DESCRIPTION
**Pull request by LizBaldo**
JIRA ticket - https://broadworkbench.atlassian.net/browse/IA-4147

I used the open api generator to generate the templates we need to convert the swagger yaml file into the java library. A bash script can then be triggered via GHA to generate and publish the leonardo java client to artifactory.

TODO:
- Test the GHA -> Make sure the library actually exists in artifactory - DONE
- Test the theoritical example usage provided in the Readme
- Fix more swagger doc issues based on what @jdcanas found - DONE

### CODE REVIEW

**Comment by LizBaldo** [comment]
@salonishah11 I published a test Snapshot version of the library here - https://broadinstitute.jfrog.io/broadinstitute/libs-release-local;build.timestamp=1679433770/org/broadinstitute/dsde/workbench/leonardo-client_2.11/1.3.5-428bb69-SNAP/leonardo-client_2.11-1.3.5-428bb69-SNAP-tests-sources.jar

Would you be okay with reviewing this PR, and maybe share with me the use case you would like to test?

**Comment by salonishah11** [comment]
@LizBaldo I can definitely review this PR!
> maybe share with me the use case you would like to test?

The test case would mostly be CBAS calling Leo's `api/apps/v2/{workspaceId}` to get a list of apps running in the workspace to figure out the WDS proxy url.

**Review by jdcanas — APPROVED** [review]

**Review by salonishah11 — APPROVED** [review]
LGTM

**Comment by LizBaldo** [comment]
jenkins retest

**Comment by LizBaldo** [comment]
Merging this to unblock folks who need that library published, and the automation test failures are unrelated

**Pull request merged**
