### PR TITLE
[PROD-848] Change all 5 second timeouts to unique durations

### PR DESCRIPTION
**Pull request by mlilynolting**
Jira ticket: [https://broadworkbench.atlassian.net/browse/[ticket_number]](https://broadworkbench.atlassian.net/browse/PROD-848)

Timeouts and timeoutlike durations to unique millisecond counts per Jack's advice.

ProxyDAO is bumped to ~6s in hopes of actually reducing the occurrence of the issue (if ProxyDAO is the culprit - I was sadly unable to reproduce in my BEE).

Something is occasionally timing out on create/start of GCP runtimes and apps, with the mysterious alert "failed due to 5 seconds." This is a TimeoutException; it's thrown by the `timeout()` method and possibly elsewhere. I changed occurrences of 5-second durations to unique values to see if this can help us pinpoint the behavior. https://console.cloud.google.com/monitoring/alerting/policies/1601022952764179214?project=broad-dsde-dev is an example of an alert which will help us notice these when they occur and use them to debug.

### Who tested and where

- [ ] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [ ] I validated this change 
- [ ] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

### CODE REVIEW

**Comment by mlilynolting** [comment]
jenkins multi-test

**Review by LizBaldo — COMMENTED** [review]
Does this mean that https://github.com/DataBiosphere/leonardo/pull/3497 is no longer relevant and should be closed? It would be nice if this PR could link the PROD ticket and explain the relationship with the PR above.

I understand the logic behind this, but I am hesitant to put something a bit messy like this in PROD, especially if we cannot reproduce successfully.

If you want to go this way, then this needs to be paired with a google alert based on the logs you would expect for each of these scenario and have the alert ping to our slack channel so we can monitor.

Also make sure to link the TODO with the ticket number to every timeout that you modified in this PR

**Comment by mlilynolting** [comment]
These 3 swat runs overlaid come to at least 2 successful runs for every test in the automation suite. The failures are known failure modes independent of the changes. I'm confident calling these automation tests passed.
https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/56251/consoleFull
https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/56257/testReport/
https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/56261/testReport/

**Comment by mlilynolting** [comment]
@LizBaldo comments added. I made a sample Alert for dev (I haven't seen this in dev yet ofc); please have a look and let me know if anything ought to change before I make production ones: https://console.cloud.google.com/monitoring/alerting/policies/1601022952764179214?project=broad-dsde-dev

**Comment by mlilynolting** [comment]
Closed for now. If https://github.com/DataBiosphere/leonardo/pull/3497/files proves not to resolve the issue may resurrect.

**Pull request closed without merging**
