### PR TITLE
IA-3138 Bump AoU image cache to 2.0.7 / 2.0.4

### PR DESCRIPTION
**Pull request by calbach**
https://broadworkbench.atlassian.net/browse/IA-3138

### CODE REVIEW

**Review by Qi77Qi — APPROVED** [review]
lgtm if automation tests pass

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by calbach** [comment]
No idea what this error means:

```
terra-quality-9c0c0dbe/automation-test-aa5x5fkzz errored due to List(RuntimeError(Failed to create cluster terra-quality-9c0c0dbe/automation-test-aa5x5fkzz due to io.grpc.StatusRuntimeException: FAILED_PRECONDITION: Feature 'Component: DOCKER' not available on cluster 'automation-test-aa5x5fkzz'. Please try a newer image version, or contact support if you have any questions,None,2021-12-14T22:17:19Z,None))
```

but either way I will likely sideline this PR for https://github.com/DataBiosphere/leonardo/pull/2466

**Comment by yonghaoy** [comment]
multi-test

**Comment by yonghaoy** [comment]
multi-test

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
fiab-stop failed.. jenkins retest

**Comment by calbach** [comment]
🎉 thank you!

**Pull request merged**
