### PR TITLE
[No Ticket] Upgrade to latest workbench-libs for better error logging

### PR DESCRIPTION
**Pull request by kyuksel**
From [Slack thread](https://broadinstitute.slack.com/archives/C02K3FWAS1Y/p1637159532237900):

image

### CODE REVIEW

**Comment by kyuksel** [comment]
multi-test

**Comment by kyuksel** [comment]
multi-test

**Comment by kyuksel** [comment]
multi-test

**Review by xuscrbw — APPROVED** [review]
LGTM

**Pull request merged**
