### PR TITLE
IA-1953 enable more automation tests

### PR DESCRIPTION
**Pull request by Qi77Qi**
https://broadworkbench.atlassian.net/browse/IA-1953

cc @gpcarr this enables rkernelspec and bioconductorspec

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by Qi77Qi** [comment]
fiab-start failure...jenkins retest

**Review by gpcarr — APPROVED** [review]

**Comment by gpcarr** [comment]
lgtm 👍

**Review by rtitle — APPROVED** [review]

**Comment by Qi77Qi** [comment]
merged https://github.com/broadinstitute/firecloud-automated-testing/pull/121..jenkins retest...

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
canceled the wrong run....jenkins retest

**Comment by Qi77Qi** [comment]
timed out waiting for fiab...jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Pull request merged**
