### PR TITLE
[QA-1597] Update GKE version

### PR DESCRIPTION
**Pull request by rtitle**
Looks like `1.18` was discontinued. :( I think this was causing automation tests to fail.

See https://cloud.google.com/kubernetes-engine/docs/release-notes

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by xuscrbw — APPROVED** [review]
lgtm

**Review by Qi77Qi — APPROVED** [review]
thanks!

**Review by cjllanwarne — APPROVED** [review]
Awesome!

**Comment by rtitle** [comment]
Darn a couple Galaxy creation failures.. testing locally to see if there are other issues, jenkins retest in the meantime

**Comment by rtitle** [comment]
jenkins retest

**Pull request merged**
