### PR TITLE
[RW-8920] Update AoU staging hostname

### PR DESCRIPTION
**Pull request by yonghaoy**
AoU is updating hostname: https://all-of-us-rw-staging.appspot.com`

to new host name: `staging.fake-research-aou.org`

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by Qi77Qi — APPROVED** [review]

**Comment by Qi77Qi** [comment]
fiab-start failure

jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Comment by yonghaoy** [comment]
jenkins retest

**Comment by yonghaoy** [comment]
jenkins retest

**Comment by yonghaoy** [comment]
jenkins retest

**Comment by yonghaoy** [comment]
jenkins retest

**Comment by yonghaoy** [comment]
jenkins retest

**Comment by yonghaoy** [comment]
@Qi77Qi any ideas on this test failing. Seem SAM is unavailable.

**Comment by Qi77Qi** [comment]
we were having some CI issues after switching to running swatomation on BEEs...might related

**Pull request merged**
