### PR TITLE
[No Ticket] Consolidate Scala Steward PRs

### PR DESCRIPTION
**Pull request by kyuksel**
Excluded `http4sVersion` upgrade (to `1.0.0-M31`) due to dependency issues

### CODE REVIEW

**Comment by kyuksel** [comment]
Looks like a transient swatomation error: 

```
12:19:54 Error: Get https://github.com/kubernetes/ingress-nginx/releases/download/helm-chart-3.23.0/ingress-nginx-3.23.0.tgz: read tcp 172.17.0.1:49736->140.82.112.4:443: read: connection timed out
12:19:54 helm.go:84: [debug] Get https://github.com/kubernetes/ingress-nginx/releases/download/helm-chart-3.23.0/ingress-nginx-3.23.0.tgz: read tcp 172.17.0.1:49736->140.82.112.4:443: read: connection timed out
12:19:54 The command '/bin/sh -c cd /leonardo &&     helm pull terra-app-setup-charts/terra-app-setup --version $TERRA_APP_SETUP_VERSION --untar &&     helm pull galaxy/galaxykubeman --version $GALAXY_VERSION --untar &&     helm pull terra/terra-app --version $TERRA_APP_VERSION --untar  &&     helm pull ingress-nginx/ingress-nginx --version $NGINX_VERSION --untar &&     helm pull cromwell-helm/cromwell --version $CROMWELL_CHART_VERSION --untar &&     cd /' returned a non-zero code: 1
```

jenkins-retest

**Review by Qi77Qi — APPROVED** [review]

**Comment by kyuksel** [comment]
I see some [Selenium errors](https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/44753/console) with no test being reported as failing 🤔 

```
org.openqa.selenium.chrome.ChromeOptions.addArguments(java.lang.String[])' (2 minutes, 7 seconds)
[info]   java.lang.NoSuchMethodError: 'org.openqa.selenium.chrome.ChromeOptions 
```

jenkins-retest

**Comment by kyuksel** [comment]
jenkins-retest

**Comment by kyuksel** [comment]
```
org.broadinstitute.dsde.workbench.leonardo.runtimes.RuntimeAutopauseSpec.autopause should work

Error Message
terra-quality-d44ee9bd/automation-test-ace35ds3z errored due to List(RuntimeError(Failed to create cluster terra-quality-d44ee9bd/automation-test-ace35ds3z due to Multiple exceptions were thrown (2), first com.google.cloud.storage.StorageException: Read timed out,None,2022-02-08T21:24:12Z,None))
```

jenkins-retest

**Comment by kyuksel** [comment]
`fiab-start` failure 

jenkins-retest

**Comment by kyuksel** [comment]
jenkins-retest

**Pull request merged**
