### PR TITLE
IA-2592: Update to Galaxy v21.01

### PR DESCRIPTION
**Pull request by rtitle**
https://broadworkbench.atlassian.net/browse/IA-2592

Update to `galaxykubeman` `1.0.0` chart corresponding to the Galaxy `21.01` release.

Marked `do not merge` because it's still pointing at a development gkm chart, we should swap to the finalized chart when ready.

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by rtitle** [comment]
`galaxy-init-db` and `galaxy-init-mounts` jobs are currently failing with:
```
Back-off pulling image "galaxy/galaxy-anvil:21.01"	BackOff	May 5, 2021, 11:05:47 AM	May 5, 2021, 11:06:12 AM	5	
Error: ImagePullBackOff	Failed	May 5, 2021, 11:05:47 AM	May 5, 2021, 11:06:12 AM	5	
Error: ErrImagePull	Failed	May 5, 2021, 11:05:43 AM	May 5, 2021, 11:05:59 AM	2	
Failed to pull image "galaxy/galaxy-anvil:21.01": rpc error: code = Unknown desc = Error response from daemon: manifest for galaxy/galaxy-anvil:21.01 not found: manifest unknown: manifest unknown
```

Sent the error the Alex, may need a chart fix I'm guessing.

**Comment by rtitle** [comment]
This works in a fiab:
image

Hopefully auto tests will pass too. 

We should probably hold off merging though until the charts are in the right location & the final Galaxy release is cut. But hopefully the Leo side is all good to go.

**Review by kyuksel — APPROVED** [review]
LGTM pending `TODO`s  👍🏼 

We'll also want to update the Galaxy version hardcoded in the UI once these changes are deployed. Makes me wonder if we should expose some sort of app version info on Leo APIs (not as part of this ticket) so we don't have to manually maintain the version on the UI.

**Comment by rtitle** [comment]
jenkins retest

**Comment by rtitle** [comment]
Re-tested locally in a fiab, it seems to work well.

**Review by Qi77Qi — APPROVED** [review]
do we need to update UI's version? maybe should create a ticket about having the version string returned from leo also

**Comment by rtitle** [comment]
@Qi77Qi done here: https://github.com/DataBiosphere/terra-ui/pull/2487

**Pull request merged**
