### PR TITLE
IA-1684  allow data uri

### PR DESCRIPTION
**Pull request by Qi77Qi**
Add `data:` to `script-src`

Screen Shot 2020-03-10 at 8 36 46 PM

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by rtitle — APPROVED** [review]
Approving but I wonder if there are any security issues with including arbitrary `data:` in `'unsafe-eval'`..

**Review by kyuksel — COMMENTED** [review]
I wonder if `data:` could be a more restricted regex if there is a known pattern that would suffice.

**Comment by Qi77Qi** [comment]
@rtitle @kyuksel updated it to `script-src 'self' data:text/javascript 'unsafe-inline' 'unsafe-eval' https://apis.google.com`

**Comment by kyuksel** [comment]
> updated it to script-src 'self' data:text/javascript 'unsafe-inline' 'unsafe-eval' https://apis.google.com

That looks better but I don't know if it may still pose too much of a security risk. Reading [this thread](https://security.stackexchange.com/questions/94993/is-including-the-data-scheme-in-your-content-security-policy-safe) didn't make me feel good. I wonder if @adrazhi would like to weigh in.

**Comment by Qi77Qi** [comment]
had a conversation with @adrazhi , and we're good to go...created https://broadworkbench.atlassian.net/browse/IA-1763, and https://broadworkbench.atlassian.net/browse/IA-1762 as follow up for hardening CSP.

**Pull request merged**
