### PR TITLE
[IA-3973] add instrumentation enabled config to CoA config

### PR DESCRIPTION
**Pull request by n8landolt**
Add instrumentationEnabled flag to be sent to Cromwell on Azure helmchart.

Jira Ticket:
https://broadworkbench.atlassian.net/browse/IA-3973

Slack Context:
https://broadinstitute.slack.com/archives/CA3NP1733/p1674147162451939

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by LizBaldo — APPROVED** [review]
LGTM! 👍 once the unit test passes

**Review by jdcanas — APPROVED** [review]

**Comment by n8landolt** [comment]
jenkins retest

**Comment by n8landolt** [comment]
jenkins retest

**Comment by n8landolt** [comment]
jenkins retest

**Comment by n8landolt** [comment]
jenkins retest

**Pull request merged**
