### PR TITLE
automated config hash updates

### PR DESCRIPTION
**Pull request by jdcanas**
https://github.com/DataBiosphere/terra-docker/pull/43

Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by Qi77Qi** [comment]
Can you link the terra-docker pr here and add ticket number here

**Review by Qi77Qi — APPROVED** [review]
👍once ci passes

**Comment by jdcanas** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
doesn't look like those images are published properly `us.gcr.io/broad-dsp-gcr-public/terra-jupyter-python:0.0.2`

**Pull request closed without merging**
