### PR TITLE
Run the Jupyter user script as privileged

### PR DESCRIPTION
**Pull request by calbach**
https://broadworkbench.atlassian.net/browse/IA-1013

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by calbach** [comment]
I can't see the Jenkins output unfortunately, I'll need someone to read it to me.

**Comment by vkumra-broad** [comment]
jenkins retest

**Comment by calbach** [comment]
@vkumra-broad or @MatthewBemis can you check whether this is a real failure?

**Comment by MatthewBemis** [comment]
It's failing because it still can't build your Docker image. I will kick the build off manually and re-run these tests once it's ready. Sorry about this, it seems to be an issue with permissions

**Comment by calbach** [comment]
OK - feel free to steal my branch and push your own PR if would be easier.

**Comment by MatthewBemis** [comment]
jenkins retest

**Pull request closed without merging**
