### PR TITLE
IA-3032 fix dataproc timeout

### PR DESCRIPTION
**Pull request by Qi77Qi**
https://broadworkbench.atlassian.net/browse/IA-3032

See https://github.com/broadinstitute/workbench-libs/pull/796

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by kyuksel — APPROVED** [review]

**Review by jdcanas — APPROVED** [review]

**Comment by Qi77Qi** [comment]
multi-test

**Comment by Qi77Qi** [comment]
multi-test

**Comment by Qi77Qi** [comment]
jenkins retest...a few fiab test failure, and one sam related failure

**Comment by Qi77Qi** [comment]
tests are failure a lot..so merging the fix with SNAP version of wb-libs...will update hash once I get approval for wb-libs change tmr

**Pull request merged**
