### PR TITLE
[WM-2056] Fix the config path for Dockstore base url

### PR DESCRIPTION
**Pull request by salonishah11**
__Jira ticket__: https://broadworkbench.atlassian.net/browse/WM-2056

## Summary of changes

This PR fixes the path to `dockstore-base-url` in `leo.conf`

### What

Bug fix for WM-2056

### Why

Bug fix for WM-2056

### What to test

One can test these changes by creating a BEE and manually updating the Leo version. 

### Who tested and where

I tested this change in a BEE by manually updating Leo versions. 
Clicking on Dockstore button opens the Staging dockstore which Leo got from Terra Helmfile charts
Screenshot 2023-06-27 at 6 07 14 PM
Screenshot 2023-06-27 at 6 07 40 PM

- [ ] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [x] I validated this change 
- [ ] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

### CODE REVIEW

**Comment by salonishah11** [comment]
jenkins retest

**Comment by salonishah11** [comment]
jenkins retest

**Comment by salonishah11** [comment]
jenkins retest

**Comment by salonishah11** [comment]
jenkins retest

**Comment by salonishah11** [comment]
jenkins retest

**Comment by salonishah11** [comment]
jenkins retest

**Review by davidangb — APPROVED** [review]

**Review by kpierre13 — APPROVED** [review]

**Review by jdcanas — APPROVED** [review]

**Pull request merged**
