### PR TITLE
Update WDS version to 0.38.0

### PR DESCRIPTION
**Pull request by broadbot**
This PR is auto-generated by
[terra-helmfile actions/make_leo_pr](https://github.com/broadinstitute/terra-helmfile/blob/main/.github/workflows/make_leo_pr.yml), using
[github actions/github-script](https://github.com/actions/github-script).

It updates WDS from chart version 0.36.0 to 0.38.0.

### CODE REVIEW

**Review by Qi77Qi — APPROVED** [review]

**Comment by jdcanas** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
```
14:22:09  error="7 execution errors:\nrawls-backend-app: Command \"KUBECONFIG=/root/.thelma/config/kubecfg kubectl --context jenkins-swat-leo-10195 --namespace terra-jenkins-swat-leo-10195 logs --selector deployment=rawls-backend --container rawls-backend-app\" exited with status 1:\nError from server (BadRequest): container \"rawls-backend-app\" in pod \"rawls-backend-deployment-69d9c55489-mtk2c\" is waiting to start: PodInitializing\n\nrawls-backend-proxy: Command \"KUBECONFIG=/root/.thelma/config/kubecfg kubectl --context jenkins-swat-leo-10195 --namespace terra-jenkins-swat-leo-10195 logs --selector deployment=rawls-backend --container rawls-backend-proxy\" exited with status 1:\nError from server (BadRequest): container \"rawls-backend-proxy\" in pod \"rawls-backend-deployment-69d9c55489-mtk2c\" is waiting to start: PodInitializing\n\nstatsd-exporter: Command \"KUBECONFIG=/root/.thelma/config/kubecfg kubectl --context jenkins-swat-leo-10195 --namespace terra-jenkins-swat-leo-10195 logs --selector deployment=rawls-backend --container statsd-exporter\" exited with status 1:\nError from server (BadRequest): container \"statsd-exporter\" in pod \"rawls-backend-deployment-69d9c55489-mtk2c\" is waiting to start: PodInitializing\n\nagora-app: Command \"KUBECONFIG=/root/.thelma/config/kubecfg kubectl --context jenkins-swat-leo-10195 --namespace terra-jenkins-swat-leo-10195 logs --selector deployment=agora-deployment --container agora-app\" exited with status 1:\nError from server (BadRequest): container \"agora-app\" in pod \"agora-deployment-547587bbcb-g8mvd\" is waiting to start: PodInitializing\n\nagora-proxy: Command \"KUBECONFIG=/root/.thelma/config/kubecfg kubectl --context jenkins-swat-leo-10195 --namespace terra-jenkins-swat-leo-10195 logs --selector deployment=agora-deployment --container agora-proxy\" exited with status 1:\nError from server (BadRequest): container \"agora-proxy\" in pod \"agora-deployment-547587bbcb-g8mvd\" is waiting to start: PodInitializing\n\ncromiam-app: Command \"KUBECONFIG=/root/.thelma/config/kubecfg kubectl --context jenkins-swat-leo-10195 --namespace terra-jenkins-swat-leo-10195 logs --selector deployment=cromiam-deployment --container cromiam-app\" exited with status 1:\nError from server (BadRequest): container \"cromiam-app\" in pod \"cromiam-deployment-59f456f99f-rc2pl\" is waiting to start: PodInitializing\n\ncromiam-proxy: Command \"KUBECONFIG=/root/.thelma/config/kubecfg kubectl --context jenkins-swat-leo-10195 --namespace terra-jenkins-swat-leo-10195 logs --selector deployment=cromiam-deployment --container cromiam-proxy\" exited with status 1:\nError from server (BadRequest): container \"cromiam-proxy\" in pod \"cromiam-deployment-59f456f99f-rc2pl\" is waiting to start: PodInitializing\n\n"
```

jenkins retest

**Comment by Qi77Qi** [comment]
more fiab-start failure

jenkins retest

**Comment by katiewelch** [comment]
jenkins retest

**Comment by Qi77Qi** [comment]
jenkins retest

**Pull request merged**
