### PR TITLE
[IA-3675] Fix saturn iframe referer check in a BEE

### PR DESCRIPTION
**Pull request by rtitle**
https://broadworkbench.atlassian.net/browse/IA-3675

Leo runtimes weren't launching in a BEE due to: 
```
{
  "source": "leonardo",
  "message": "Invalid `saturn-iframe-extension` https://terra.fiab-rtitle-sound-loon.bee.envs-terra.bio/jupyter-iframe-extension.js",
  "statusCode": 400,
  "exceptionClass": "class org.broadinstitute.dsde.workbench.leonardo.model.BadRequestException",
  "traceId": "5f9cb539-c5f6-4ba3-b0aa-af9043a19e0c"
}
```

I think this is because the BEE hostname isn't in the RefererConfig. However the RefererConfig includes a special character `*` which we set in fiab environments. We similarly check this in `ProxyRoutes` [here](https://github.com/DataBiosphere/leonardo/blob/develop/http/src/main/scala/org/broadinstitute/dsde/workbench/leonardo/http/api/ProxyRoutes.scala#L294) -- this adds an equivalent check for `saturn-iframe-extension`.

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green (you can re-run automation tests with a comment saying `jenkins retest`
- [ ] Run the automation tests multiple times in parallel to weed out instability if applicable via a comment saying `multi-test`
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by rtitle** [comment]
jenkins retest

**Review by Qi77Qi — COMMENTED** [review]
does this mean if any url that contains `*`, it'll pass referer and the saturn iframe check?

**Comment by rtitle** [comment]
No, the url is like `https://terra.fiab-rtitle-sound-loon.bee.envs-terra.bio/jupyter-iframe-extension.js`, but since the referer config has `*` in it ([link](https://github.com/broadinstitute/firecloud-develop/blob/dev/base-configs/leonardo/leonardo.conf.ctmpl#L271)), it'll always pass.

**Review by Qi77Qi — APPROVED** [review]
I see..so this is saying if the "all valid saturn iframe extensions from config" includes `*`, then we're allowing everything

**Pull request merged**
